//! Dossier mode — parasite's "understands people" workspace.
//!
//! Type a subject (a person, organization or place) and parasite assembles a
//! readable profile from a stack of sources:
//!   • Wikipedia REST summary  → title, one-line description, lead paragraph, photo
//!   • Wikidata claims         → structured biography (born/died, citizenship,
//!                                occupation, education, employer, awards, socials)
//!   • a user-supplied JSON DB  → your own records, merged on top
//!
//! The result is rendered as an animated, card-based report and can be exported
//! to Markdown, JSON, PNG and PDF (the latter two reuse the graph's screenshot
//! pipeline). This is an experimental feature.

use std::collections::{BTreeMap, HashMap, HashSet};
use std::sync::mpsc::{Receiver, Sender};
use std::time::Duration;

use eframe::egui::{self, Color32, Margin, RichText, Rounding, ScrollArea, Stroke};
use serde::{Deserialize, Serialize};
use serde_json::Value;

use super::i18n::{self, translate, Lang};
use super::theme::*;

// ── Data model ──────────────────────────────────────────────────────────────

#[derive(Serialize, Clone)]
pub struct Section {
    pub title: String,
    pub icon:  &'static str,
    pub facts: Vec<(String, String)>,
}

#[derive(Serialize, Clone, Default)]
pub struct Dossier {
    pub title:        String,
    pub subtitle:     String,
    pub summary:      String,
    pub sections:     Vec<Section>,
    pub links:        Vec<(String, String)>,
    pub more:         Vec<(String, String)>,
    pub source_label: String,
    pub url:          Option<String>,
    pub thumb_url:    Option<String>,
}

impl Dossier {
    fn empty(query: &str) -> Self {
        Self { title: query.to_string(), ..Default::default() }
    }

    fn to_markdown(&self) -> String {
        let mut s = String::new();
        s.push_str(&format!("# {}\n\n", self.title));
        if !self.subtitle.is_empty() { s.push_str(&format!("*{}*\n\n", self.subtitle)); }
        if !self.source_label.is_empty() {
            s.push_str(&format!("> Sources: {}\n\n", self.source_label));
        }
        if !self.summary.is_empty() { s.push_str(&format!("{}\n\n", self.summary)); }
        for sec in &self.sections {
            s.push_str(&format!("## {} {}\n\n", sec.icon, sec.title));
            for (k, v) in &sec.facts { s.push_str(&format!("- **{k}:** {v}\n")); }
            s.push('\n');
        }
        if !self.links.is_empty() {
            s.push_str("## ❖ Links\n\n");
            for (k, v) in &self.links { s.push_str(&format!("- **{k}:** {v}\n")); }
            s.push('\n');
        }
        if !self.more.is_empty() {
            s.push_str("## ⊕ More sources\n\n");
            for (k, v) in &self.more { s.push_str(&format!("- **{k}:** {v}\n")); }
            s.push('\n');
        }
        s.push_str("---\n_Generated by parasite · Dossier mode_\n");
        s
    }
}

/// A record in a user-supplied JSON database.
#[derive(Deserialize, Default)]
struct CustomRecord {
    #[serde(default)] name:    String,
    #[serde(default)] aka:     Vec<String>,
    #[serde(default)] role:    Option<String>,
    #[serde(default)] summary: Option<String>,
    #[serde(default)] facts:   BTreeMap<String, String>,
    #[serde(default)] links:   BTreeMap<String, String>,
}

#[derive(Deserialize)]
struct CustomWrapper { #[serde(default)] records: Vec<CustomRecord> }

// ── Worker → UI messages ────────────────────────────────────────────────────

enum DMsg {
    Log(String),
    Done(Box<Dossier>),
    Thumb(Vec<u8>),
    Failed(String),
    Ai(Result<String, String>),
    Chat(Result<String, String>),
    Sites(String),
}

/// A dossier handed to the graph (when graph sync is on).
pub struct DossierSeed {
    pub title:    String,
    pub subtitle: String,
    pub is_org:   bool,
    pub facts:    Vec<(String, String)>,
    pub links:    Vec<(String, String)>,
}

const ORG_HINTS: &[&str] = &["company", "organization", "organisation", "corporation",
    "firm", "enterprise", "agency", "university", "institute", "studio", "team",
    "компания", "организация", "корпорация", "agency", "організація", "компанія"];

#[derive(Clone, Copy)]
enum ExportFmt { Png, Pdf }

// ── Panel ───────────────────────────────────────────────────────────────────

pub struct DossierPanel {
    rt: tokio::runtime::Runtime,
    tx: Sender<DMsg>,
    rx: Receiver<DMsg>,

    query:       String,
    db_path:     String,
    custom_db:   Vec<CustomRecord>,
    loading:     bool,
    status:      String,
    log:         Vec<String>,

    dossier:     Option<Dossier>,
    error:       Option<String>,
    sync_graph:  bool,
    pending_seed: Option<DossierSeed>,
    toast:       Option<(String, f64)>,
    ai_summary:  Option<String>,
    ai_busy:     bool,
    show_chat:   bool,
    chat:        Vec<(super::ai::ChatRole, String)>,
    chat_input:  String,
    chat_busy:   bool,
    site_ctx:    Option<String>,
    sites_busy:  bool,
    thumb:       Option<egui::TextureHandle>,
    thumb_bytes: Option<Vec<u8>>,
    anim_start:  f64,

    pending_shot: Option<ExportFmt>,
    panel_rect:   egui::Rect,
}

impl DossierPanel {
    pub fn new() -> Self {
        let rt = tokio::runtime::Builder::new_multi_thread()
            .worker_threads(2).enable_all().build().expect("tokio runtime");
        let (tx, rx) = std::sync::mpsc::channel();
        Self {
            rt, tx, rx,
            query: String::new(),
            db_path: "people.json".into(),
            custom_db: Vec::new(),
            loading: false,
            status: "ready".into(),
            log: Vec::new(),
            dossier: None,
            error: None,
            sync_graph: false,
            pending_seed: None,
            toast: None,
            ai_summary: None,
            ai_busy: false,
            show_chat: false,
            chat: Vec::new(),
            chat_input: String::new(),
            chat_busy: false,
            site_ctx: None,
            sites_busy: false,
            thumb: None,
            thumb_bytes: None,
            anim_start: 0.0,
            pending_shot: None,
            panel_rect: egui::Rect::NOTHING,
        }
    }

    fn logline(&mut self, s: impl Into<String>) {
        self.log.push(s.into());
        if self.log.len() > 200 { self.log.drain(0..self.log.len() - 200); }
    }

    /// Hand a finished dossier to the graph (consumed by the Shell once).
    pub fn take_seed(&mut self) -> Option<DossierSeed> { self.pending_seed.take() }

    /// Ask the configured AI to write an intelligence assessment of the dossier.
    fn build_ai_summary(&mut self) {
        let Some(d) = &self.dossier else { return };
        let Some(cfg) = super::ai::cfg() else {
            self.status = "no AI key — add Claude/Gemini in Settings".into(); return;
        };
        let mut facts = format!("Subject: {}\n{}\n\n{}\n", d.title, d.subtitle, d.summary);
        for s in &d.sections {
            facts.push_str(&format!("\n{}:\n", s.title));
            for (k, v) in &s.facts { facts.push_str(&format!("  {k}: {v}\n")); }
        }
        for (k, v) in &d.links { facts.push_str(&format!("  link {k}: {v}\n")); }
        let system = "You are an OSINT analyst. Given the collected dossier facts, write a concise \
                      intelligence assessment: who this is, the key takeaways, notable connections or \
                      gaps, and concrete next investigative steps. Be factual, flag uncertainty, and \
                      do not invent details not supported by the facts. Plain prose, ~150 words.".to_string();
        self.ai_busy = true;
        self.status = format!("asking {}…", cfg.label());
        let tx = self.tx.clone();
        self.rt.spawn(async move {
            let res = super::ai::complete(&cfg, &system, &facts).await;
            let _ = tx.send(DMsg::Ai(res));
        });
    }

    /// System prompt for the dossier chat: the facts + (optionally) the fetched
    /// source-page text, so the model can analyze the actual sites.
    fn chat_system(&self) -> String {
        let mut s = String::from("You are an OSINT analyst chatting with an investigator about a \
            subject. Answer their questions using the dossier facts and any source page text below. \
            Be precise, cite which source a claim comes from when possible, flag uncertainty, and \
            never invent details not present in the material. You analyse only — never export, save \
            files, or run commands.\n\n");
        if let Some(d) = &self.dossier {
            s.push_str(&format!("=== DOSSIER ===\nSubject: {}\n{}\n{}\n", d.title, d.subtitle, d.summary));
            for sec in &d.sections {
                for (k, v) in &sec.facts { s.push_str(&format!("{k}: {v}\n")); }
            }
            for (k, v) in d.links.iter().chain(d.more.iter()) {
                s.push_str(&format!("source {k}: {v}\n"));
            }
        }
        if let Some(sites) = &self.site_ctx {
            s.push_str("\n=== SOURCE PAGE TEXT ===\n");
            s.push_str(sites);
        }
        s
    }

    fn send_chat(&mut self) {
        let msg = self.chat_input.trim().to_string();
        if msg.is_empty() || self.chat_busy { return; }
        let Some(cfg) = super::ai::cfg() else {
            self.status = "no AI key set".into(); return;
        };
        self.chat.push((super::ai::ChatRole::User, msg));
        self.chat_input.clear();
        let system = self.chat_system();
        let history = self.chat.clone();
        let tx = self.tx.clone();
        self.chat_busy = true;
        self.rt.spawn(async move {
            let res = super::ai::chat(&cfg, &system, &history).await;
            let _ = tx.send(DMsg::Chat(res));
        });
    }

    /// Fetch the text of every dossier source so the chat can analyze the sites.
    fn fetch_sites(&mut self) {
        let Some(d) = &self.dossier else { return };
        if self.sites_busy { return; }
        let urls: Vec<(String, String)> = d.links.iter().chain(d.more.iter())
            .filter(|(_, u)| u.starts_with("http"))
            .map(|(k, u)| (k.clone(), u.clone())).collect();
        if urls.is_empty() { self.status = "no source URLs to fetch".into(); return; }
        self.sites_busy = true;
        self.status = format!("fetching {} source(s)…", urls.len().min(6));
        let tx = self.tx.clone();
        self.rt.spawn(async move {
            let text = super::ai::fetch_sites(urls).await;
            let _ = tx.send(DMsg::Sites(text));
        });
    }

    fn build(&mut self, query: String) {
        let q = query.trim().to_string();
        if q.is_empty() { self.status = "type a subject first".into(); return; }
        self.query = q.clone();
        self.loading = true;
        self.dossier = None;
        self.error = None;
        self.thumb = None;
        self.thumb_bytes = None;
        self.ai_summary = None;
        self.chat.clear();
        self.site_ctx = None;
        self.status = format!("assembling dossier on “{q}” …");
        self.logline(format!("▸  building dossier: {q}"));
        let lang = i18n::lang();

        // hand the custom DB to the worker as plain records it can match against
        let custom: Vec<(String, Vec<String>, Option<String>, Option<String>,
                          Vec<(String, String)>, Vec<(String, String)>)> =
            self.custom_db.iter().map(|r| (
                r.name.clone(), r.aka.clone(), r.role.clone(), r.summary.clone(),
                r.facts.iter().map(|(k, v)| (k.clone(), v.clone())).collect(),
                r.links.iter().map(|(k, v)| (k.clone(), v.clone())).collect(),
            )).collect();

        let tx = self.tx.clone();
        self.rt.spawn(async move { fetch(q, custom, lang, tx).await; });
    }

    fn load_db(&mut self) {
        let path = self.db_path.trim().to_string();
        if path.is_empty() { self.status = "enter a database path".into(); return; }
        match std::fs::read_to_string(&path) {
            Ok(text) => {
                let recs = serde_json::from_str::<Vec<CustomRecord>>(&text)
                    .or_else(|_| serde_json::from_str::<CustomWrapper>(&text).map(|w| w.records));
                match recs {
                    Ok(r) => {
                        let n = r.len();
                        self.custom_db = r;
                        self.status = format!("loaded {n} record(s) from {path}");
                        self.logline(format!("✓  custom DB: {n} record(s)"));
                    }
                    Err(e) => {
                        self.status = format!("DB parse error: {e}");
                        self.logline(format!("✗  DB parse error: {e}"));
                    }
                }
            }
            Err(e) => {
                self.status = format!("cannot read {path}: {e}");
                self.logline(format!("✗  cannot read {path}: {e}"));
            }
        }
    }

    fn drain(&mut self, ctx: &egui::Context) {
        while let Ok(m) = self.rx.try_recv() {
            match m {
                DMsg::Log(s) => self.logline(s),
                DMsg::Done(d) => {
                    self.loading = false;
                    self.status = format!("✓  dossier ready — {}", d.source_label);
                    self.logline(format!("✓  dossier ready ({} section(s))", d.sections.len()));
                    self.anim_start = ctx.input(|i| i.time);
                    if self.sync_graph {
                        self.pending_seed = Some(seed_of(&d));
                        self.toast = Some((i18n::tr("dos.added_graph").to_string(), self.anim_start));
                    }
                    self.dossier = Some(*d);
                }
                DMsg::Thumb(bytes) => {
                    if let Ok(img) = image::load_from_memory(&bytes) {
                        let rgba = img.to_rgba8();
                        let size = [rgba.width() as usize, rgba.height() as usize];
                        let ci = egui::ColorImage::from_rgba_unmultiplied(size, &rgba);
                        self.thumb = Some(ctx.load_texture("dossier_thumb", ci,
                            egui::TextureOptions::LINEAR));
                        self.thumb_bytes = Some(bytes);
                    }
                }
                DMsg::Failed(s) => {
                    self.loading = false;
                    self.status = format!("✗  {s}");
                    self.logline(format!("✗  {s}"));
                    self.error = Some(s);
                }
                DMsg::Ai(res) => {
                    self.ai_busy = false;
                    match res {
                        Ok(t) => { self.ai_summary = Some(t); self.status = "✓  AI assessment ready".into(); }
                        Err(e) => { self.status = format!("✗  AI: {e}"); self.logline(format!("✗  AI: {e}")); }
                    }
                }
                DMsg::Chat(res) => {
                    self.chat_busy = false;
                    match res {
                        Ok(t) => self.chat.push((super::ai::ChatRole::Assistant, t)),
                        Err(e) => self.chat.push((super::ai::ChatRole::Assistant, format!("✗ {e}"))),
                    }
                }
                DMsg::Sites(text) => {
                    self.sites_busy = false;
                    let n = text.matches("===").count() / 2;
                    self.site_ctx = Some(text);
                    self.chat.push((super::ai::ChatRole::Assistant,
                        format!("⊕ Loaded {n} source page(s) — ask me to analyze them.")));
                }
            }
        }
    }

    // ── Exports ──────────────────────────────────────────────────────────────

    fn export_md(&mut self) {
        let Some(d) = &self.dossier else { self.status = "build a dossier first".into(); return };
        match std::fs::write("dossier.md", d.to_markdown()) {
            Ok(_)  => { self.status = "✓  saved dossier.md".into(); self.logline("✓  exported dossier.md"); }
            Err(e) => { self.status = format!("✗  {e}"); }
        }
    }

    fn export_json(&mut self) {
        let Some(d) = &self.dossier else { self.status = "build a dossier first".into(); return };
        match serde_json::to_string_pretty(d).map_err(|e| e.to_string())
            .and_then(|s| std::fs::write("dossier.json", s).map_err(|e| e.to_string()))
        {
            Ok(_)  => { self.status = "✓  saved dossier.json".into(); self.logline("✓  exported dossier.json"); }
            Err(e) => { self.status = format!("✗  {e}"); }
        }
    }

    fn capture(&mut self, ctx: &egui::Context, fmt: ExportFmt) {
        if self.dossier.is_none() { self.status = "build a dossier first".into(); return; }
        self.pending_shot = Some(fmt);
        ctx.send_viewport_cmd(egui::ViewportCommand::Screenshot);
        self.status = "◦  capturing dossier…".into();
    }

    fn save_shot(&mut self, img: &egui::ColorImage, fmt: ExportFmt, ppp: f32) {
        let [fw, fh] = img.size;
        let r = self.panel_rect;
        let x0 = ((r.min.x * ppp).floor() as usize).min(fw);
        let y0 = ((r.min.y * ppp).floor() as usize).min(fh);
        let x1 = ((r.max.x * ppp).ceil() as usize).min(fw);
        let y1 = ((r.max.y * ppp).ceil() as usize).min(fh);
        let (cw, ch) = (x1.saturating_sub(x0), y1.saturating_sub(y0));
        if cw == 0 || ch == 0 { self.status = "✗  empty capture".into(); return; }
        let mut rgba = Vec::with_capacity(cw * ch * 4);
        for y in y0..y1 {
            for x in x0..x1 {
                let px = img.pixels[y * fw + x];
                rgba.extend_from_slice(&[px.r(), px.g(), px.b(), 255]);
            }
        }
        let (cw, ch) = (cw as u32, ch as u32);
        let res = match fmt {
            ExportFmt::Png => super::export::save_png("dossier.png", &rgba, cw, ch).map(|_| "dossier.png"),
            ExportFmt::Pdf => super::export::save_pdf("dossier.pdf", &rgba, cw, ch).map(|_| "dossier.pdf"),
        };
        match res {
            Ok(p)  => { self.status = format!("✓  saved {p} ({cw}×{ch})"); self.logline(format!("✓  exported {p}")); }
            Err(e) => { self.status = format!("✗  export failed: {e}"); }
        }
    }

    // ── Frame ────────────────────────────────────────────────────────────────

    pub fn ui(&mut self, ctx: &egui::Context) {
        self.drain(ctx);

        // collect a pending screenshot exported on the *next* frame
        if self.pending_shot.is_some() {
            let shot = ctx.input(|i| i.events.iter().find_map(|e| match e {
                egui::Event::Screenshot { image, .. } => Some(image.clone()),
                _ => None,
            }));
            if let Some(img) = shot {
                let ppp = ctx.pixels_per_point();
                if let Some(fmt) = self.pending_shot.take() { self.save_shot(&img, fmt, ppp); }
            }
        }

        self.toolbar(ctx);
        self.statusbar(ctx);
        self.chat_panel(ctx);

        let mut trigger: Option<String> = None;
        egui::CentralPanel::default()
            .frame(egui::Frame::none().fill(bg_app()).inner_margin(Margin::same(0.0)))
            .show(ctx, |ui| {
                self.panel_rect = ui.max_rect();
                let now = ctx.input(|i| i.time);
                if self.loading {
                    loading_view(ui, now);
                    ctx.request_repaint();
                } else if let Some(d) = &self.dossier {
                    report_view(ui, d, self.thumb.as_ref(), now, self.anim_start, self.ai_summary.as_deref());
                    if now - self.anim_start < 2.5 { ctx.request_repaint(); }
                } else if let Some(err) = self.error.clone() {
                    if error_view(ui, &err) { trigger = Some(self.query.clone()); }
                } else {
                    trigger = empty_view(ui);
                }
            });

        if let Some(q) = trigger { self.build(q); }

        // transient "added to graph" toast — a fading pill at the bottom centre
        if let Some((msg, t0)) = self.toast.clone() {
            let now = ctx.input(|i| i.time);
            let age = (now - t0) as f32;
            const LIFE: f32 = 2.4;
            if age > LIFE { self.toast = None; }
            else {
                let alpha = if age < 0.2 { age / 0.2 } else { ((LIFE - age) / 0.6).clamp(0.0, 1.0) };
                let screen = ctx.screen_rect();
                egui::Area::new(egui::Id::new("dossier_toast"))
                    .order(egui::Order::Foreground)
                    .fixed_pos(egui::pos2(screen.center().x - 120.0, screen.max.y - 90.0))
                    .show(ctx, |ui| {
                        ui.set_opacity(alpha);
                        egui::Frame::none().fill(accent()).rounding(Rounding::same(10.0))
                            .inner_margin(Margin::symmetric(18.0, 10.0))
                            .stroke(Stroke::new(1.0, accent_dark()))
                            .show(ui, |ui| {
                                ui.label(RichText::new(format!("◇  {msg}"))
                                    .color(Color32::WHITE).strong().size(13.0));
                            });
                    });
                ctx.request_repaint();
            }
        }
    }

    fn toolbar(&mut self, ctx: &egui::Context) {
        egui::TopBottomPanel::top("dossier_toolbar")
            .frame(egui::Frame::none().fill(bg_sidebar())
                .inner_margin(Margin::symmetric(12.0, 8.0))
                .stroke(Stroke::new(1.0, border())))
            .show(ctx, |ui| {
                ui.horizontal(|ui| {
                    ui.label(RichText::new(format!("▤ {}", i18n::tr("dos.subject"))).color(text_sec()).size(12.0));
                    let resp = ui.add(egui::TextEdit::singleline(&mut self.query)
                        .desired_width(280.0).hint_text(i18n::tr("dos.subject_hint")));
                    let go_key = resp.lost_focus() && ui.input(|i| i.key_pressed(egui::Key::Enter));
                    if tbtn(ui, &format!("⊙ {}", i18n::tr("dos.build")), accent()).clicked() || go_key {
                        let q = self.query.clone();
                        self.build(q);
                    }

                    ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                        let have = self.dossier.is_some();
                        if tbtn_on(ui, "▣ PDF", have).clicked()  { self.capture(ctx, ExportFmt::Pdf); }
                        if tbtn_on(ui, "▣ PNG", have).clicked()  { self.capture(ctx, ExportFmt::Png); }
                        if tbtn_on(ui, "⇩ JSON", have).clicked() { self.export_json(); }
                        if tbtn_on(ui, "⇩ MD", have).clicked()   { self.export_md(); }
                    });
                });

                ui.add_space(5.0);
                ui.horizontal(|ui| {
                    ui.label(RichText::new(format!("▦ {}", i18n::tr("dos.custom_db"))).color(text_sec()).size(12.0));
                    ui.add(egui::TextEdit::singleline(&mut self.db_path)
                        .desired_width(220.0).hint_text(i18n::tr("dos.db_path_hint")));
                    if tbtn(ui, &format!("▤ {}", i18n::tr("dos.load")), text_sec()).clicked() { self.load_db(); }
                    let dbinfo = if self.custom_db.is_empty() {
                        i18n::tr("dos.no_db").to_string()
                    } else {
                        format!("✓ {} ✓", self.custom_db.len())
                    };
                    ui.label(RichText::new(dbinfo).color(text_mut()).size(11.0).italics());

                    ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                        if tbtn_on(ui, &format!("◇ {}", i18n::tr("dos.to_graph")), self.dossier.is_some()).clicked() {
                            if let Some(d) = &self.dossier {
                                self.pending_seed = Some(seed_of(d));
                                self.toast = Some((i18n::tr("dos.added_graph").to_string(),
                                    ui.input(|i| i.time)));
                            }
                        }
                        let ai_label = if self.ai_busy { format!("◌ {}", i18n::tr("dos.ai_working")) }
                                       else { format!("✦ {}", i18n::tr("dos.ai")) };
                        if tbtn_on(ui, &ai_label, self.dossier.is_some() && !self.ai_busy).clicked() {
                            self.build_ai_summary();
                        }
                        if tbtn_on(ui, &format!("❝ {}", i18n::tr("dos.chat")), self.dossier.is_some()).clicked() {
                            self.show_chat = !self.show_chat;
                        }
                        ui.checkbox(&mut self.sync_graph,
                            RichText::new(i18n::tr("dos.sync_graph")).color(text_sec()).size(11.5));
                    });
                });
            });
    }

    fn statusbar(&mut self, ctx: &egui::Context) {
        egui::TopBottomPanel::bottom("dossier_status")
            .frame(egui::Frame::none().fill(bg_sidebar())
                .inner_margin(Margin::symmetric(12.0, 5.0))
                .stroke(Stroke::new(1.0, border())))
            .show(ctx, |ui| {
                ui.horizontal(|ui| {
                    ui.label(RichText::new(&self.status).color(text_sec()).size(11.5));
                    ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                        if let Some(last) = self.log.last() {
                            ui.label(RichText::new(last).color(text_mut()).size(11.0).monospace());
                        }
                    });
                });
            });
    }

    /// The dossier chat — a resizable right panel for a full conversation with the
    /// AI about the subject, with optional "analyze the source sites" context.
    fn chat_panel(&mut self, ctx: &egui::Context) {
        if !self.show_chat || self.dossier.is_none() { return; }
        let mut send = false;
        let mut fetch = false;
        let mut clear = false;
        let mut quick: Option<&str> = None;
        egui::SidePanel::right("dossier_chat")
            .resizable(true).default_width(330.0).width_range(260.0..=460.0)
            .frame(egui::Frame::none().fill(bg_panel()).stroke(Stroke::new(1.0, border())))
            .show(ctx, |ui| {
                // header
                egui::TopBottomPanel::top("dchat_hdr")
                    .frame(egui::Frame::none().fill(bg_sidebar())
                        .inner_margin(Margin::symmetric(12.0, 7.0)).stroke(Stroke::new(1.0, border())))
                    .show_inside(ui, |ui| {
                        ui.horizontal(|ui| {
                            ui.label(RichText::new(format!("❝ {}", i18n::tr("dos.chat_title")))
                                .color(text_pri()).strong().size(13.0));
                            ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                                if tbtn(ui, "✗", text_sec()).clicked() { clear = true; }
                                let stxt = if self.sites_busy { "◌" }
                                           else if self.site_ctx.is_some() { "⊕✓" } else { "⊕" };
                                if tbtn(ui, stxt, text_sec()).on_hover_text(i18n::tr("dos.chat_sites")).clicked() { fetch = true; }
                            });
                        });
                    });
                // input docked at bottom
                egui::TopBottomPanel::bottom("dchat_in")
                    .frame(egui::Frame::none().fill(bg_input())
                        .inner_margin(Margin::symmetric(8.0, 7.0)).stroke(Stroke::new(1.0, border())))
                    .show_inside(ui, |ui| {
                        ui.horizontal(|ui| {
                            let r = ui.add(egui::TextEdit::singleline(&mut self.chat_input)
                                .desired_width(ui.available_width() - 56.0)
                                .hint_text(i18n::tr("dos.chat_ph")));
                            let enter = r.lost_focus() && ui.input(|i| i.key_pressed(egui::Key::Enter));
                            let click = ui.add_enabled(!self.chat_busy, egui::Button::new(
                                RichText::new("➤").color(Color32::WHITE).strong())
                                .fill(accent()).rounding(Rounding::same(corner()))).clicked();
                            if (enter || click) && !self.chat_input.trim().is_empty() { send = true; r.request_focus(); }
                        });
                    });
                // quick chips
                egui::TopBottomPanel::top("dchat_chips")
                    .frame(egui::Frame::none().inner_margin(Margin::symmetric(8.0, 5.0)))
                    .show_inside(ui, |ui| {
                        ui.horizontal_wrapped(|ui| {
                            for (icon, prompt) in [
                                ("✦ Summarize", "Give a concise intelligence summary of this subject."),
                                ("⚠ Risks", "What are the notable risks, red flags or inconsistencies?"),
                                ("➡ Next steps", "What concrete next investigative steps do you suggest?"),
                                ("⊕ Analyze sites", "Analyze the source pages and tell me what stands out."),
                            ] {
                                if ui.add(egui::Button::new(RichText::new(icon).color(text_sec()).size(11.0))
                                    .fill(bg_item_hov()).stroke(Stroke::new(1.0, border()))
                                    .rounding(Rounding::same(12.0))).clicked() { quick = Some(prompt); }
                            }
                        });
                    });
                // messages
                egui::CentralPanel::default()
                    .frame(egui::Frame::none().inner_margin(Margin::symmetric(10.0, 8.0)))
                    .show_inside(ui, |ui| {
                        ScrollArea::vertical().auto_shrink([false; 2]).stick_to_bottom(true).show(ui, |ui| {
                            ui.set_width(ui.available_width());
                            if self.chat.is_empty() {
                                ui.label(RichText::new(i18n::tr("dos.chat_hello")).color(text_mut()).size(11.5).italics());
                            }
                            for (role, text) in &self.chat {
                                let me = *role == super::ai::ChatRole::User;
                                let (fill, col) = if me { (bg_item_sel(), text_pri()) } else { (bg_item_hov(), text_sec()) };
                                egui::Frame::none().fill(fill).rounding(Rounding::same(8.0))
                                    .inner_margin(Margin::symmetric(10.0, 7.0)).show(ui, |ui| {
                                        ui.set_width(ui.available_width());
                                        ui.label(RichText::new(if me { "you" } else { "ai" })
                                            .color(if me { accent() } else { c_info() }).size(9.5).strong());
                                        ui.label(RichText::new(text).color(col).size(12.5));
                                    });
                                ui.add_space(5.0);
                            }
                            if self.chat_busy {
                                ui.horizontal(|ui| {
                                    super::logo::widget_anim(ui, 13.0);
                                    ui.add_space(4.0);
                                    ui.label(RichText::new("thinking…").color(text_mut()).size(11.5).italics());
                                });
                            }
                        });
                    });
            });
        if clear { self.chat.clear(); }
        if fetch { self.fetch_sites(); }
        if let Some(p) = quick { if !self.chat_busy { self.chat_input = p.to_string(); self.send_chat(); } }
        if send { self.send_chat(); }
        if self.chat_busy || self.sites_busy { ctx.request_repaint(); }
    }
}

// ── Stateless views (free fns to dodge borrow conflicts) ─────────────────────

fn ease_out_cubic(t: f32) -> f32 { 1.0 - (1.0 - t).powi(3) }

/// Build the graph seed from a dossier: subject + its links + a few key facts.
fn seed_of(d: &Dossier) -> DossierSeed {
    let sub = d.subtitle.to_lowercase();
    let is_org = ORG_HINTS.iter().any(|h| sub.contains(h));
    let facts: Vec<(String, String)> = d.sections.iter()
        .flat_map(|s| s.facts.iter().cloned()).take(12).collect();
    DossierSeed {
        title: d.title.clone(),
        subtitle: d.subtitle.clone(),
        is_org,
        facts,
        links: d.links.clone(),
    }
}

fn empty_view(ui: &mut egui::Ui) -> Option<String> {
    let mut picked = None;
    ui.vertical_centered(|ui| {
        ui.add_space(70.0);
        super::logo::widget(ui, 40.0);
        ui.add_space(14.0);
        ui.label(RichText::new(i18n::tr("dos.title")).color(text_pri()).strong().size(30.0));
        ui.add_space(4.0);
        ui.label(RichText::new(i18n::tr("dos.tagline1")).color(text_sec()).size(13.0));
        ui.label(RichText::new(i18n::tr("dos.tagline2")).color(text_sec()).size(13.0));
        ui.add_space(22.0);
        ui.label(RichText::new(i18n::tr("dos.try")).color(accent()).size(10.5).strong());
        ui.add_space(8.0);
        ui.horizontal(|ui| {
            let w = ui.available_width();
            ui.add_space((w - 560.0).max(0.0) / 2.0);
            for ex in ["Linus Torvalds", "Ada Lovelace", "OpenAI", "Berlin", "Grace Hopper"] {
                if ui.add(egui::Button::new(RichText::new(ex).color(text_pri()).size(12.5))
                    .fill(bg_item_hov()).stroke(Stroke::new(1.0, border()))
                    .rounding(Rounding::same(14.0))).clicked()
                {
                    picked = Some(ex.to_string());
                }
            }
        });
        ui.add_space(26.0);
        ui.label(RichText::new(format!("⚠  {}", i18n::tr("dos.warn")))
            .color(text_mut()).size(10.5).italics());
    });
    picked
}

/// Shown when no source returned anything. Returns true if the user hit "retry".
fn error_view(ui: &mut egui::Ui, msg: &str) -> bool {
    let mut retry = false;
    ui.vertical_centered(|ui| {
        ui.add_space(120.0);
        ui.label(RichText::new("⊘").color(c_err()).size(46.0));
        ui.add_space(10.0);
        ui.label(RichText::new(i18n::tr("dos.not_found")).color(text_pri()).strong().size(22.0));
        ui.add_space(4.0);
        ui.label(RichText::new(i18n::tr("dos.not_found_hint")).color(text_sec()).size(13.0));
        ui.add_space(6.0);
        ui.label(RichText::new(msg).color(text_mut()).size(11.5).monospace());
        ui.add_space(18.0);
        if ui.add(egui::Button::new(RichText::new(format!("↻ {}", i18n::tr("dos.retry")))
            .color(Color32::WHITE).strong().size(13.0))
            .fill(accent()).rounding(Rounding::same(8.0))).clicked()
        {
            retry = true;
        }
    });
    retry
}

fn loading_view(ui: &mut egui::Ui, now: f64) {
    ui.vertical_centered(|ui| {
        ui.add_space(140.0);
        super::logo::widget_anim(ui, 34.0);
        ui.add_space(16.0);
        let dots = ".".repeat(1 + (now * 2.0) as usize % 3);
        ui.label(RichText::new(format!("{}{dots}", i18n::tr("dos.reading")))
            .color(text_sec()).size(14.0));
    });
}

fn report_view(ui: &mut egui::Ui, d: &Dossier, thumb: Option<&egui::TextureHandle>,
               now: f64, anim_start: f64, ai: Option<&str>) {
    ScrollArea::vertical().auto_shrink([false; 2]).show(ui, |ui| {
        ui.add_space(18.0);
        let max = (ui.available_width() - 48.0).min(900.0).max(320.0);
        let pad = (ui.available_width() - max).max(0.0) / 2.0;
        ui.horizontal(|ui| {
            ui.add_space(pad);
            ui.vertical(|ui| {
                ui.set_width(max);

                // index 0 = hero, then one per section, then links card
                anim_card(ui, 0, now, anim_start, |ui| hero(ui, d, thumb));

                // AI assessment (when generated) — sits right under the hero
                if let Some(text) = ai {
                    anim_card(ui, 1, now, anim_start, |ui| {
                        section_header(ui, "✦", i18n::tr("dos.ai_title"));
                        ui.add_space(4.0);
                        ui.label(RichText::new(text).color(text_pri()).size(13.0));
                    });
                }

                if !d.summary.is_empty() {
                    anim_card(ui, 1, now, anim_start, |ui| {
                        section_header(ui, "✎", i18n::tr("sec.summary"));
                        ui.add_space(4.0);
                        ui.label(RichText::new(&d.summary).color(text_pri()).size(13.5));
                    });
                }

                let mut idx = if d.summary.is_empty() { 1 } else { 2 };
                for sec in d.sections.iter() {
                    anim_card(ui, idx, now, anim_start, |ui| {
                        section_header(ui, sec.icon, &sec.title);
                        ui.add_space(4.0);
                        for (k, v) in &sec.facts { fact_row(ui, k, v); }
                    });
                    idx += 1;
                }

                if !d.links.is_empty() {
                    anim_card(ui, idx, now, anim_start, |ui| {
                        section_header(ui, "❖", i18n::tr("sec.links"));
                        ui.add_space(4.0);
                        for (k, url) in &d.links { link_row(ui, k, url); }
                    });
                    idx += 1;
                }

                if !d.more.is_empty() {
                    anim_card(ui, idx, now, anim_start, |ui| {
                        section_header(ui, "⊕", i18n::tr("sec.more"));
                        ui.add_space(4.0);
                        for (k, url) in &d.more { link_row(ui, k, url); }
                    });
                }

                ui.add_space(24.0);
            });
        });
    });
}

/// Render `body` inside a framed card with a staggered fade-and-rise reveal.
fn anim_card(ui: &mut egui::Ui, idx: usize, now: f64, anim_start: f64,
             body: impl FnOnce(&mut egui::Ui)) {
    let dur = 0.5;
    let delay = idx as f64 * 0.09;
    let t = (((now - anim_start - delay) / dur).clamp(0.0, 1.0)) as f32;
    let e = ease_out_cubic(t);
    ui.add_space(8.0 + (1.0 - e) * 14.0);
    ui.scope(|ui| {
        ui.set_opacity(e.max(0.02));
        egui::Frame::none()
            .fill(bg_panel())
            .stroke(Stroke::new(1.0, border()))
            .rounding(Rounding::same(12.0))
            .inner_margin(Margin::symmetric(18.0, 14.0))
            .show(ui, |ui| {
                ui.set_width(ui.available_width());
                body(ui);
            });
    });
}

fn hero(ui: &mut egui::Ui, d: &Dossier, thumb: Option<&egui::TextureHandle>) {
    ui.horizontal(|ui| {
        if let Some(tex) = thumb {
            let st = egui::load::SizedTexture::new(tex.id(), tex.size_vec2());
            ui.add(egui::Image::new(st)
                .fit_to_exact_size(egui::vec2(104.0, 104.0))
                .rounding(Rounding::same(10.0)));
            ui.add_space(14.0);
        } else {
            // placeholder disc with the subject's initial
            let (rect, _) = ui.allocate_exact_size(egui::vec2(104.0, 104.0), egui::Sense::hover());
            ui.painter().rect_filled(rect, Rounding::same(10.0), bg_item_hov());
            ui.painter().rect_stroke(rect, Rounding::same(10.0), Stroke::new(1.0, border()));
            let ch = d.title.chars().next().unwrap_or('?').to_uppercase().to_string();
            ui.painter().text(rect.center(), egui::Align2::CENTER_CENTER, ch,
                egui::FontId::proportional(44.0), accent());
            ui.add_space(14.0);
        }
        ui.vertical(|ui| {
            ui.add_space(6.0);
            ui.label(RichText::new(&d.title).color(text_pri()).strong().size(24.0));
            if !d.subtitle.is_empty() {
                ui.label(RichText::new(&d.subtitle).color(accent()).size(14.0));
            }
            ui.add_space(6.0);
            if !d.source_label.is_empty() {
                egui::Frame::none().fill(bg_item_hov()).rounding(Rounding::same(10.0))
                    .inner_margin(Margin::symmetric(8.0, 3.0)).show(ui, |ui| {
                        ui.label(RichText::new(format!("◈ {}", d.source_label))
                            .color(text_sec()).size(10.5).strong());
                    });
            }
        });
    });
}

fn section_header(ui: &mut egui::Ui, icon: &str, title: &str) {
    ui.horizontal(|ui| {
        ui.label(RichText::new(icon).size(15.0));
        ui.add_space(2.0);
        ui.label(RichText::new(title).color(text_pri()).strong().size(14.5));
    });
    let r = ui.min_rect();
    let y = r.bottom() + 3.0;
    ui.painter().line_segment([egui::pos2(r.left(), y), egui::pos2(r.right(), y)],
        Stroke::new(1.0, border()));
}

fn fact_row(ui: &mut egui::Ui, k: &str, v: &str) {
    ui.horizontal_wrapped(|ui| {
        ui.add_sized([140.0, 18.0], egui::Label::new(
            RichText::new(k).color(text_sec()).size(12.5)).halign(egui::Align::LEFT));
        ui.label(RichText::new(v).color(text_pri()).size(12.5));
    });
}

fn link_row(ui: &mut egui::Ui, k: &str, url: &str) {
    ui.horizontal_wrapped(|ui| {
        ui.add_sized([140.0, 18.0], egui::Label::new(
            RichText::new(k).color(text_sec()).size(12.5)).halign(egui::Align::LEFT));
        let r = ui.add(egui::Label::new(RichText::new(url).color(c_info()).size(12.5))
            .sense(egui::Sense::click()));
        if r.hovered() { ui.ctx().set_cursor_icon(egui::CursorIcon::PointingHand); }
        if r.clicked() { super::app_open(url); }
    });
}

// ── Toolbar button helpers ───────────────────────────────────────────────────

fn tbtn(ui: &mut egui::Ui, label: &str, col: Color32) -> egui::Response {
    let r = ui.add(egui::Button::new(RichText::new(label).color(col).size(12.0).strong())
        .fill(bg_input()).stroke(Stroke::new(1.0, border())).rounding(Rounding::same(corner())));
    if r.hovered() { ui.ctx().set_cursor_icon(egui::CursorIcon::PointingHand); }
    r
}

fn tbtn_on(ui: &mut egui::Ui, label: &str, enabled: bool) -> egui::Response {
    let col = if enabled { text_sec() } else { text_mut() };
    ui.add_enabled(enabled, egui::Button::new(RichText::new(label).color(col).size(12.0))
        .fill(bg_input()).stroke(Stroke::new(1.0, border())).rounding(Rounding::same(corner())))
}

// ── The async source pipeline ────────────────────────────────────────────────

type RawRecord = (String, Vec<String>, Option<String>, Option<String>,
                  Vec<(String, String)>, Vec<(String, String)>);

fn client() -> reqwest::Client {
    super::net::builder()
        .user_agent("parasite-dossier/1.0 (open-source OSINT toolkit)")
        .timeout(Duration::from_secs(20))
        .gzip(true)
        .build()
        .expect("client")
}

/// Percent-encode a string for a URL query value (spaces → %20).
fn qenc(s: &str) -> String {
    let mut o = String::new();
    for b in s.bytes() {
        match b {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => o.push(b as char),
            _ => o.push_str(&format!("%{b:02X}")),
        }
    }
    o
}

/// Top-N candidate article titles for a query in one language.
async fn wiki_candidates(client: &reqwest::Client, lang: &str, query: &str, limit: u32) -> Vec<String> {
    let url = format!("https://{lang}.wikipedia.org/w/api.php?action=query&list=search&srsearch={}&srlimit={limit}&format=json&origin=*", qenc(query));
    let j: Value = match client.get(&url).send().await {
        Ok(r) => match r.json().await { Ok(j) => j, Err(_) => return Vec::new() },
        Err(_) => return Vec::new(),
    };
    j["query"]["search"].as_array().map(|a| a.iter()
        .filter_map(|x| x["title"].as_str().map(|s| s.to_string())).collect()).unwrap_or_default()
}

/// Crude relevance score of a candidate title to the user's query (case- and
/// order-insensitive token matching, with bonuses for prefix/exact matches).
fn title_score(query: &str, title: &str) -> i32 {
    let q = query.trim().to_lowercase();
    let t = title.to_lowercase();
    if t == q { return 1000; }
    let mut s = 0;
    if t.starts_with(&q) || q.starts_with(&t) { s += 450; }
    let qt: Vec<&str> = q.split_whitespace().filter(|w| w.len() > 1).collect();
    let mut hit = 0;
    for w in &qt { if t.contains(w) { s += 130; hit += 1; } }
    if !qt.is_empty() && hit == qt.len() { s += 200; } // all query words present
    s -= (t.chars().count() as i32 - q.chars().count() as i32).abs() / 3;
    s
}

/// Resolve a free-text query to the best Wikipedia (lang, title). Searches both
/// the app language and English (script-aware order) and ranks candidates, so
/// e.g. "linus torvald" → ("en","Linus Torvalds") even with a Russian UI.
async fn wiki_resolve(client: &reqwest::Client, app: &str, query: &str) -> Option<(String, String)> {
    let has_cyrillic = query.chars().any(|c| ('\u{0400}'..='\u{04FF}').contains(&c));
    let langs: [&str; 2] = if has_cyrillic { [app, "en"] } else { ["en", app] };
    let mut best: Option<(String, String, i32)> = None;
    let mut seen: Vec<&str> = Vec::new();
    for l in langs {
        if seen.contains(&l) { continue; }
        seen.push(l);
        for t in wiki_candidates(client, l, query, 5).await {
            let sc = title_score(query, &t);
            if best.as_ref().map(|b| sc > b.2).unwrap_or(true) {
                best = Some((l.to_string(), t, sc));
            }
        }
    }
    best.map(|(l, t, _)| (l, t))
}

/// Percent-encode a Wikipedia title for a path segment (spaces → underscore).
fn enc(s: &str) -> String {
    let mut o = String::new();
    for b in s.bytes() {
        match b {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => o.push(b as char),
            b' ' => o.push('_'),
            _ => o.push_str(&format!("%{b:02X}")),
        }
    }
    o
}

async fn fetch(query: String, custom: Vec<RawRecord>, lang: Lang, tx: Sender<DMsg>) {
    let client = client();
    let mut d = Dossier::empty(&query);
    let mut got = false;
    let mut thumb_url: Option<String> = None;

    // 1 ── Resolve the query to a real article title first (this is the "smart"
    // part: it fixes casing like "linus torvalds", typos and partial names), then
    // fetch the summary. Try the app language, then English.
    // Build an ordered list of (lang, title) attempts: the ranked search hit
    // first, then the raw query in the app language and in English.
    let mut attempts: Vec<(String, String)> = Vec::new();
    if let Some((l, t)) = wiki_resolve(&client, lang.code(), &query).await {
        let _ = tx.send(DMsg::Log(format!("◦  best match: {l}:{t}")));
        attempts.push((l, t));
    }
    attempts.push((lang.code().to_string(), query.clone()));
    if lang.code() != "en" { attempts.push(("en".to_string(), query.clone())); }

    let mut summary: Option<Value> = None;
    for (l, t) in &attempts {
        let url = format!("https://{l}.wikipedia.org/api/rest_v1/page/summary/{}", enc(t));
        match client.get(&url).send().await {
            Ok(r) if r.status().is_success() => match r.json::<Value>().await {
                Ok(j) if j["type"].as_str() == Some("disambiguation") => {
                    let _ = tx.send(DMsg::Log(format!("⚠  “{t}” is a disambiguation page — trying next")));
                }
                Ok(j) => { summary = Some(j); break; }
                Err(_) => {}
            },
            Ok(_) => {}
            Err(e) => { let _ = tx.send(DMsg::Log(format!("✗  Wikipedia error: {e}"))); }
        }
    }
    match summary {
        Some(j) => {
            got = true;
            d.title = j["title"].as_str().unwrap_or(&query).to_string();
            if let Some(s) = j["description"].as_str() { d.subtitle = s.to_string(); }
            if let Some(s) = j["extract"].as_str() { d.summary = s.to_string(); }
            d.url = j["content_urls"]["desktop"]["page"].as_str().map(|s| s.to_string());
            thumb_url = j["thumbnail"]["source"].as_str().map(|s| s.to_string());
            d.source_label = "Wikipedia".into();
            if let Some(u) = d.url.clone() { d.links.push(("Wikipedia".into(), u)); }
            let _ = tx.send(DMsg::Log(format!("✓  Wikipedia: {}", d.title)));

            // 2 ── Wikidata structured facts + cross-language sources
            if let Some(qid) = j["wikibase_item"].as_str() {
                let _ = tx.send(DMsg::Log(format!("◦  Wikidata {qid}…")));
                if let Some((mut secs, links, mut more, img)) =
                    fetch_wikidata(&client, qid, lang).await
                {
                    d.sections.append(&mut secs);
                    for l in links { if !d.links.iter().any(|(k, _)| *k == l.0) { d.links.push(l); } }
                    d.more.append(&mut more);
                    if thumb_url.is_none() { thumb_url = img; }
                    d.source_label = "Wikipedia + Wikidata".into();
                    let _ = tx.send(DMsg::Log("✓  Wikidata facts merged".into()));
                }
            }
        }
        None => { let _ = tx.send(DMsg::Log(format!("◦  no Wikipedia page for “{query}”"))); }
    }

    // 3 ── Custom database overlay
    if let Some((name, _, role, summary, facts, links)) = match_custom(&custom, &query) {
        got = true;
        if d.title.is_empty() { d.title = name; }
        if d.subtitle.is_empty() { if let Some(r) = role { d.subtitle = r; } }
        if d.summary.is_empty() { if let Some(s) = summary { d.summary = s; } }
        if !facts.is_empty() {
            d.sections.push(Section { title: translate(lang, "sec.custom").into(), icon: "▦", facts });
        }
        for (k, v) in links { if !d.links.iter().any(|(lk, _)| *lk == k) { d.links.push((k, v)); } }
        d.source_label = if d.source_label.is_empty() {
            "Custom DB".into()
        } else {
            format!("{} + Custom DB", d.source_label)
        };
        let _ = tx.send(DMsg::Log("✓  matched a custom database record".into()));
    }

    if !got {
        let _ = tx.send(DMsg::Failed(format!("nothing found for “{query}”")));
        return;
    }

    // discovery links — always available, so the report points further out
    let qs = query.trim().replace(' ', "+");
    d.more.push((translate(lang, "l.web_search").to_string(),
                 format!("https://duckduckgo.com/?q={qs}")));
    d.more.push(("Google".into(), format!("https://www.google.com/search?q={qs}")));

    d.thumb_url = thumb_url.clone();
    let _ = tx.send(DMsg::Done(Box::new(d)));

    // 4 ── thumbnail (fetched after the card is shown so it pops in)
    if let Some(tu) = thumb_url {
        if let Ok(resp) = client.get(&tu).send().await {
            if let Ok(bytes) = resp.bytes().await {
                let _ = tx.send(DMsg::Thumb(bytes.to_vec()));
            }
        }
    }
}

/// Find the first custom record whose name / aka matches the query.
fn match_custom(custom: &[RawRecord], query: &str) -> Option<RawRecord> {
    let q = query.trim().to_lowercase();
    custom.iter().find(|(name, aka, ..)| {
        name.to_lowercase() == q
            || name.to_lowercase().contains(&q)
            || aka.iter().any(|a| a.to_lowercase() == q)
    }).cloned()
}

/// Pull a curated, human-readable set of facts from a Wikidata entity.
/// Labels are resolved in the app language (falling back to English), and the
/// section/fact captions are translated. Returns (sections, links, more, image).
async fn fetch_wikidata(client: &reqwest::Client, qid: &str, lang: Lang)
    -> Option<(Vec<Section>, Vec<(String, String)>, Vec<(String, String)>, Option<String>)>
{
    let url = format!("https://www.wikidata.org/wiki/Special:EntityData/{qid}.json");
    let j: Value = client.get(&url).send().await.ok()?.json().await.ok()?;
    let entity = j["entities"][qid].clone();
    let claims = entity["claims"].clone();
    if !claims.is_object() { return None; }
    let tl = |k: &str| translate(lang, k).to_string();

    // collect entity-referencing property values so their labels can be resolved
    let ref_props = ["P21", "P19", "P20", "P27", "P106", "P108", "P69",
                     "P166", "P39", "P26", "P140", "P101"];
    let mut want: HashSet<String> = HashSet::new();
    for p in ref_props { for q in entity_ids(&claims, p) { want.insert(q); } }
    let labels = resolve_labels(client, &want, lang.code()).await;

    let lbl = |q: &str| labels.get(q).cloned().unwrap_or_else(|| q.to_string());
    let first = |p: &str| entity_ids(&claims, p).first().map(|q| lbl(q));
    let join = |p: &str, n: usize| {
        let v: Vec<String> = entity_ids(&claims, p).iter().take(n).map(|q| lbl(q)).collect();
        if v.is_empty() { None } else { Some(v.join(", ")) }
    };

    // Identity
    let mut identity = Vec::new();
    if let Some(g) = first("P21")            { identity.push((tl("f.gender"), g)); }
    if let Some(t) = time(&claims, "P569")   { identity.push((tl("f.born"), t)); }
    if let Some(b) = first("P19")            { identity.push((tl("f.birthplace"), b)); }
    if let Some(c) = join("P27", 3)          { identity.push((tl("f.citizenship"), c)); }
    if let Some(t) = time(&claims, "P570")   { identity.push((tl("f.died"), t)); }
    if let Some(b) = first("P20")            { identity.push((tl("f.death_place"), b)); }

    // Career
    let mut career = Vec::new();
    if let Some(o) = join("P106", 5) { career.push((tl("f.occupation"), o)); }
    if let Some(e) = join("P108", 3) { career.push((tl("f.employer"), e)); }
    if let Some(e) = join("P69", 3)  { career.push((tl("f.education"), e)); }
    if let Some(p) = join("P39", 3)  { career.push((tl("f.position"), p)); }
    if let Some(a) = join("P166", 5) { career.push((tl("f.awards"), a)); }

    // Personal
    let mut personal = Vec::new();
    if let Some(s) = join("P26", 3) { personal.push((tl("f.spouse"), s)); }
    if let Some(f) = first("P101")  { personal.push((tl("f.field"), f)); }
    if let Some(r) = first("P140")  { personal.push((tl("f.religion"), r)); }

    let mut sections = Vec::new();
    if !identity.is_empty() { sections.push(Section { title: tl("sec.identity"), icon: "◉", facts: identity }); }
    if !career.is_empty()   { sections.push(Section { title: tl("sec.career"),   icon: "▤", facts: career }); }
    if !personal.is_empty() { sections.push(Section { title: tl("sec.personal"), icon: "❤", facts: personal }); }

    // Online presence (string / external-id / url properties)
    let mut links = Vec::new();
    if let Some(u) = strings(&claims, "P856").into_iter().next()  { links.push((tl("l.official"), u)); }
    if let Some(u) = strings(&claims, "P2002").into_iter().next() { links.push(("Twitter / X".into(), format!("https://twitter.com/{u}"))); }
    if let Some(u) = strings(&claims, "P2037").into_iter().next() { links.push(("GitHub".into(), format!("https://github.com/{u}"))); }
    if let Some(u) = strings(&claims, "P2003").into_iter().next() { links.push(("Instagram".into(), format!("https://instagram.com/{u}"))); }
    if let Some(u) = strings(&claims, "P2013").into_iter().next() { links.push(("Facebook".into(), format!("https://facebook.com/{u}"))); }
    if let Some(u) = strings(&claims, "P345").into_iter().next()  { links.push(("IMDb".into(), format!("https://www.imdb.com/name/{u}"))); }

    // More sources — the Wikidata item itself + the article in each language
    let mut more = Vec::new();
    more.push(("Wikidata".into(), format!("https://www.wikidata.org/wiki/{qid}")));
    for (site, label) in [("enwiki", "Wikipedia (EN)"), ("ruwiki", "Wikipedia (RU)"),
                          ("ukwiki", "Wikipedia (UK)")] {
        if let Some(title) = entity["sitelinks"][site]["title"].as_str() {
            let sub = site.trim_end_matches("wiki");
            more.push((label.to_string(),
                format!("https://{sub}.wikipedia.org/wiki/{}", enc(title))));
        }
    }

    // photo (Commons image) as a thumbnail fallback
    let img = strings(&claims, "P18").into_iter().next()
        .map(|f| format!("https://commons.wikimedia.org/wiki/Special:FilePath/{}?width=400", enc(&f)));

    Some((sections, links, more, img))
}

fn entity_ids(claims: &Value, pid: &str) -> Vec<String> {
    claims[pid].as_array().map(|arr| arr.iter().filter_map(|c|
        c["mainsnak"]["datavalue"]["value"]["id"].as_str().map(|s| s.to_string())
    ).collect()).unwrap_or_default()
}

fn strings(claims: &Value, pid: &str) -> Vec<String> {
    claims[pid].as_array().map(|arr| arr.iter().filter_map(|c|
        c["mainsnak"]["datavalue"]["value"].as_str().map(|s| s.to_string())
    ).collect()).unwrap_or_default()
}

fn time(claims: &Value, pid: &str) -> Option<String> {
    let v = &claims[pid].get(0)?["mainsnak"]["datavalue"]["value"];
    let t = v["time"].as_str()?;
    let prec = v["precision"].as_u64().unwrap_or(11);
    Some(fmt_wd_time(t, prec))
}

/// Format a Wikidata time literal ("+1969-12-28T00:00:00Z") by precision.
fn fmt_wd_time(t: &str, prec: u64) -> String {
    let s = t.strip_prefix('+').unwrap_or(t);
    let date = s.split('T').next().unwrap_or(s);
    let parts: Vec<&str> = date.split('-').collect();
    match prec {
        p if p <= 9 => parts.first().copied().unwrap_or(date).to_string(),
        10          => parts.iter().take(2).copied().collect::<Vec<_>>().join("-"),
        _           => date.to_string(),
    }
}

/// Batch-resolve Wikidata Q-ids → labels in `lang` (with an English fallback).
async fn resolve_labels(client: &reqwest::Client, want: &HashSet<String>, lang: &str)
    -> HashMap<String, String>
{
    let mut out = HashMap::new();
    if want.is_empty() { return out; }
    let ids: Vec<&String> = want.iter().collect();
    for chunk in ids.chunks(50) {
        let joined = chunk.iter().map(|s| s.as_str()).collect::<Vec<_>>().join("|");
        let url = format!("https://www.wikidata.org/w/api.php?action=wbgetentities\
                           &ids={joined}&props=labels&languages={lang}|en&format=json");
        if let Ok(resp) = client.get(&url).send().await {
            if let Ok(j) = resp.json::<Value>().await {
                if let Some(ents) = j["entities"].as_object() {
                    for (q, ev) in ents {
                        let label = ev["labels"][lang]["value"].as_str()
                            .or_else(|| ev["labels"]["en"]["value"].as_str());
                        if let Some(l) = label { out.insert(q.clone(), l.to_string()); }
                    }
                }
            }
        }
    }
    out
}
