//! Auto-curated "pivot" transforms: 200+ one-click link-outs to OSINT services.
//! Each pivot turns an entity into a Website node pointing at the relevant lookup
//! page on an external service. Data-driven so the set is easy to extend.

use std::sync::OnceLock;

use super::model::Kind;
use super::transforms::TransformDef;

pub struct Pivot {
    pub id:      &'static str,
    pub name:    &'static str,
    pub applies: Kind,
    pub desc:    &'static str,
    pub url:     &'static str,   // contains a single "{}" placeholder for the value
    pub edge:    &'static str,
}

pub const PIVOTS: &[Pivot] = &[
    Pivot { id: "pv_dom_virustotal", name: "VirusTotal Domain", applies: Kind::Domain, desc: "open in VirusTotal Domain", url: "https://www.virustotal.com/gui/domain/{}", edge: "virustotal" },
    Pivot { id: "pv_dom_urlscan", name: "urlscan.io", applies: Kind::Domain, desc: "open in urlscan.io", url: "https://urlscan.io/domain/{}", edge: "urlscan" },
    Pivot { id: "pv_dom_securitytrails", name: "SecurityTrails", applies: Kind::Domain, desc: "open in SecurityTrails", url: "https://securitytrails.com/domain/{}/dns", edge: "securitytrails" },
    Pivot { id: "pv_dom_crtsh", name: "crt.sh certs", applies: Kind::Domain, desc: "open in crt.sh certs", url: "https://crt.sh/?q={}", edge: "crt.sh" },
    Pivot { id: "pv_dom_shodan", name: "Shodan", applies: Kind::Domain, desc: "open in Shodan", url: "https://www.shodan.io/search?query={}", edge: "shodan" },
    Pivot { id: "pv_dom_censys", name: "Censys", applies: Kind::Domain, desc: "open in Censys", url: "https://search.censys.io/search?resource=hosts&q={}", edge: "censys" },
    Pivot { id: "pv_dom_whois", name: "who.is WHOIS", applies: Kind::Domain, desc: "open in who.is WHOIS", url: "https://who.is/whois/{}", edge: "whois" },
    Pivot { id: "pv_dom_dnsdumpster", name: "DNSdumpster", applies: Kind::Domain, desc: "open in DNSdumpster", url: "https://dnsdumpster.com/?q={}", edge: "dnsdumpster" },
    Pivot { id: "pv_dom_builtwith", name: "BuiltWith", applies: Kind::Domain, desc: "open in BuiltWith", url: "https://builtwith.com/{}", edge: "builtwith" },
    Pivot { id: "pv_dom_wayback", name: "Wayback Machine", applies: Kind::Domain, desc: "open in Wayback Machine", url: "https://web.archive.org/web/*/{}", edge: "wayback" },
    Pivot { id: "pv_dom_otx", name: "AlienVault OTX", applies: Kind::Domain, desc: "open in AlienVault OTX", url: "https://otx.alienvault.com/indicator/domain/{}", edge: "otx" },
    Pivot { id: "pv_dom_threatcrowd", name: "ThreatCrowd", applies: Kind::Domain, desc: "open in ThreatCrowd", url: "https://threatcrowd.org/domain.php?domain={}", edge: "threatcrowd" },
    Pivot { id: "pv_dom_robtex", name: "Robtex", applies: Kind::Domain, desc: "open in Robtex", url: "https://www.robtex.com/dns-lookup/{}", edge: "robtex" },
    Pivot { id: "pv_dom_viewdns_iphistory", name: "ViewDNS IP history", applies: Kind::Domain, desc: "open in ViewDNS IP history", url: "https://viewdns.info/iphistory/?domain={}", edge: "viewdns" },
    Pivot { id: "pv_dom_netcraft", name: "Netcraft Site Report", applies: Kind::Domain, desc: "open in Netcraft Site Report", url: "https://sitereport.netcraft.com/?url={}", edge: "netcraft" },
    Pivot { id: "pv_dom_similarweb", name: "SimilarWeb", applies: Kind::Domain, desc: "open in SimilarWeb", url: "https://www.similarweb.com/website/{}", edge: "similarweb" },
    Pivot { id: "pv_dom_hackertarget", name: "HackerTarget DNS", applies: Kind::Domain, desc: "open in HackerTarget DNS", url: "https://hackertarget.com/dns-lookup/?q={}", edge: "hackertarget" },
    Pivot { id: "pv_dom_mxtoolbox", name: "MXToolbox", applies: Kind::Domain, desc: "open in MXToolbox", url: "https://mxtoolbox.com/SuperTool.aspx?action=mx%3a{}", edge: "mxtoolbox" },
    Pivot { id: "pv_dom_dnslytics", name: "DNSlytics", applies: Kind::Domain, desc: "open in DNSlytics", url: "https://dnslytics.com/domain/{}", edge: "dnslytics" },
    Pivot { id: "pv_dom_spyonweb", name: "SpyOnWeb", applies: Kind::Domain, desc: "open in SpyOnWeb", url: "https://spyonweb.com/{}", edge: "spyonweb" },
    Pivot { id: "pv_dom_urlvoid", name: "URLVoid", applies: Kind::Domain, desc: "open in URLVoid", url: "https://www.urlvoid.com/scan/{}", edge: "urlvoid" },
    Pivot { id: "pv_dom_threatminer", name: "ThreatMiner", applies: Kind::Domain, desc: "open in ThreatMiner", url: "https://www.threatminer.org/domain.php?q={}", edge: "threatminer" },
    Pivot { id: "pv_dom_pulsedive", name: "Pulsedive", applies: Kind::Domain, desc: "open in Pulsedive", url: "https://pulsedive.com/indicator/?ioc={}", edge: "pulsedive" },
    Pivot { id: "pv_dom_hostio", name: "host.io", applies: Kind::Domain, desc: "open in host.io", url: "https://host.io/{}", edge: "host.io" },
    Pivot { id: "pv_dom_talos", name: "Cisco Talos", applies: Kind::Domain, desc: "open in Cisco Talos", url: "https://talosintelligence.com/reputation_center/lookup?search={}", edge: "talos" },
    Pivot { id: "pv_dom_intodns", name: "IntoDNS", applies: Kind::Domain, desc: "open in IntoDNS", url: "https://intodns.com/{}", edge: "intodns" },
    Pivot { id: "pv_dom_ssllabs", name: "SSL Labs", applies: Kind::Domain, desc: "open in SSL Labs", url: "https://www.ssllabs.com/ssltest/analyze.html?d={}", edge: "ssllabs" },
    Pivot { id: "pv_dom_hardenize", name: "Hardenize", applies: Kind::Domain, desc: "open in Hardenize", url: "https://www.hardenize.com/report/{}", edge: "hardenize" },
    Pivot { id: "pv_dom_dnschecker", name: "DNSChecker", applies: Kind::Domain, desc: "open in DNSChecker", url: "https://dnschecker.org/all-dns-records-of-domain.php?query={}&rtype=ALL", edge: "dnschecker" },
    Pivot { id: "pv_dom_whoxy", name: "Whoxy WHOIS", applies: Kind::Domain, desc: "open in Whoxy WHOIS", url: "https://www.whoxy.com/{}", edge: "whoxy" },
    Pivot { id: "pv_dom_validin", name: "Validin", applies: Kind::Domain, desc: "open in Validin", url: "https://app.validin.com/detail?find={}", edge: "validin" },
    Pivot { id: "pv_dom_urlhaus", name: "URLhaus", applies: Kind::Domain, desc: "open in URLhaus", url: "https://urlhaus.abuse.ch/browse.php?search={}", edge: "urlhaus" },
    Pivot { id: "pv_dom_webcheck", name: "Web-Check", applies: Kind::Domain, desc: "open in Web-Check", url: "https://web-check.xyz/results/{}", edge: "web-check" },
    Pivot { id: "pv_dom_expireddomains", name: "ExpiredDomains", applies: Kind::Domain, desc: "open in ExpiredDomains", url: "https://www.expireddomains.net/domain-name-search/?q={}", edge: "expireddomains" },
    Pivot { id: "pv_dom_bgpview", name: "BGPView search", applies: Kind::Domain, desc: "open in BGPView search", url: "https://bgpview.io/search/{}", edge: "bgpview" },
    Pivot { id: "pv_dom_cloudflare_radar", name: "Cloudflare Radar", applies: Kind::Domain, desc: "open in Cloudflare Radar", url: "https://radar.cloudflare.com/domains/domain/{}", edge: "cloudflare" },
    Pivot { id: "pv_dom_shodan_favicon", name: "Shodan favicon", applies: Kind::Domain, desc: "open in Shodan favicon", url: "https://www.shodan.io/search?query=hostname%3A{}", edge: "shodan" },
    Pivot { id: "pv_dom_dorks_google", name: "Google site: dork", applies: Kind::Domain, desc: "open in Google site: dork", url: "https://www.google.com/search?q=site%3A{}", edge: "google" },
    Pivot { id: "pv_dom_subdomainfinder", name: "Subdomain Finder", applies: Kind::Domain, desc: "open in Subdomain Finder", url: "https://subdomainfinder.c99.nl/scans/{}", edge: "c99" },
    Pivot { id: "pv_dom_dnsviz", name: "DNSViz", applies: Kind::Domain, desc: "open in DNSViz", url: "https://dnsviz.net/d/{}/dnssec/", edge: "dnsviz" },
    Pivot { id: "pv_ip_shodan", name: "Shodan host", applies: Kind::Ip, desc: "open in Shodan host", url: "https://www.shodan.io/host/{}", edge: "shodan" },
    Pivot { id: "pv_ip_censys", name: "Censys host", applies: Kind::Ip, desc: "open in Censys host", url: "https://search.censys.io/hosts/{}", edge: "censys" },
    Pivot { id: "pv_ip_virustotal", name: "VirusTotal IP", applies: Kind::Ip, desc: "open in VirusTotal IP", url: "https://www.virustotal.com/gui/ip-address/{}", edge: "virustotal" },
    Pivot { id: "pv_ip_abuseipdb", name: "AbuseIPDB", applies: Kind::Ip, desc: "open in AbuseIPDB", url: "https://www.abuseipdb.com/check/{}", edge: "abuseipdb" },
    Pivot { id: "pv_ip_greynoise", name: "GreyNoise", applies: Kind::Ip, desc: "open in GreyNoise", url: "https://viz.greynoise.io/ip/{}", edge: "greynoise" },
    Pivot { id: "pv_ip_ipinfo", name: "IPinfo", applies: Kind::Ip, desc: "open in IPinfo", url: "https://ipinfo.io/{}", edge: "ipinfo" },
    Pivot { id: "pv_ip_ipdata", name: "ipdata", applies: Kind::Ip, desc: "open in ipdata", url: "https://ipdata.co/?ip={}", edge: "ipdata" },
    Pivot { id: "pv_ip_criminalip", name: "Criminal IP", applies: Kind::Ip, desc: "open in Criminal IP", url: "https://www.criminalip.io/asset/report/{}", edge: "criminalip" },
    Pivot { id: "pv_ip_otx", name: "AlienVault OTX IP", applies: Kind::Ip, desc: "open in AlienVault OTX IP", url: "https://otx.alienvault.com/indicator/ip/{}", edge: "otx" },
    Pivot { id: "pv_ip_robtex", name: "Robtex IP", applies: Kind::Ip, desc: "open in Robtex IP", url: "https://www.robtex.com/ip-lookup/{}", edge: "robtex" },
    Pivot { id: "pv_ip_viewdns_reverseip", name: "ViewDNS reverse IP", applies: Kind::Ip, desc: "open in ViewDNS reverse IP", url: "https://viewdns.info/reverseip/?host={}&t=1", edge: "viewdns" },
    Pivot { id: "pv_ip_bgphe", name: "Hurricane BGP", applies: Kind::Ip, desc: "open in Hurricane BGP", url: "https://bgp.he.net/ip/{}", edge: "he.net" },
    Pivot { id: "pv_ip_spur", name: "Spur", applies: Kind::Ip, desc: "open in Spur", url: "https://spur.us/context/{}", edge: "spur" },
    Pivot { id: "pv_ip_ipqs", name: "IPQualityScore", applies: Kind::Ip, desc: "open in IPQualityScore", url: "https://www.ipqualityscore.com/ip-reputation-check/lookup/{}", edge: "ipqs" },
    Pivot { id: "pv_ip_ipvoid", name: "IPVoid", applies: Kind::Ip, desc: "open in IPVoid", url: "https://www.ipvoid.com/ip-blacklist-check/?ip={}", edge: "ipvoid" },
    Pivot { id: "pv_ip_talos", name: "Talos IP", applies: Kind::Ip, desc: "open in Talos IP", url: "https://talosintelligence.com/reputation_center/lookup?search={}", edge: "talos" },
    Pivot { id: "pv_ip_internetdb", name: "Shodan InternetDB", applies: Kind::Ip, desc: "open in Shodan InternetDB", url: "https://internetdb.shodan.io/{}", edge: "shodan" },
    Pivot { id: "pv_ip_scamalytics", name: "Scamalytics", applies: Kind::Ip, desc: "open in Scamalytics", url: "https://scamalytics.com/ip/{}", edge: "scamalytics" },
    Pivot { id: "pv_ip_fofa", name: "FOFA", applies: Kind::Ip, desc: "open in FOFA", url: "https://en.fofa.info/result?qbase64=&q={}", edge: "fofa" },
    Pivot { id: "pv_ip_zoomeye", name: "ZoomEye", applies: Kind::Ip, desc: "open in ZoomEye", url: "https://www.zoomeye.org/searchResult?q={}", edge: "zoomeye" },
    Pivot { id: "pv_ip_onyphe", name: "ONYPHE", applies: Kind::Ip, desc: "open in ONYPHE", url: "https://www.onyphe.io/search/?q={}", edge: "onyphe" },
    Pivot { id: "pv_ip_ipgeolocation", name: "IPGeolocation", applies: Kind::Ip, desc: "open in IPGeolocation", url: "https://ipgeolocation.io/ip-location/{}", edge: "ipgeolocation" },
    Pivot { id: "pv_ip_dnslytics", name: "DNSlytics IP", applies: Kind::Ip, desc: "open in DNSlytics IP", url: "https://dnslytics.com/ip/{}", edge: "dnslytics" },
    Pivot { id: "pv_ip_hackertarget_reverse", name: "HackerTarget reverse", applies: Kind::Ip, desc: "open in HackerTarget reverse", url: "https://hackertarget.com/reverse-ip-lookup/?q={}", edge: "hackertarget" },
    Pivot { id: "pv_ip_threatminer", name: "ThreatMiner IP", applies: Kind::Ip, desc: "open in ThreatMiner IP", url: "https://www.threatminer.org/host.php?q={}", edge: "threatminer" },
    Pivot { id: "pv_ip_pulsedive", name: "Pulsedive IP", applies: Kind::Ip, desc: "open in Pulsedive IP", url: "https://pulsedive.com/indicator/?ioc={}", edge: "pulsedive" },
    Pivot { id: "pv_ip_shodan_maps", name: "Shodan Maps", applies: Kind::Ip, desc: "open in Shodan Maps", url: "https://www.shodan.io/search?query=ip%3A{}", edge: "shodan" },
    Pivot { id: "pv_ip_censys_cert", name: "Censys certs", applies: Kind::Ip, desc: "open in Censys certs", url: "https://search.censys.io/search?resource=hosts&q={}", edge: "censys" },
    Pivot { id: "pv_ip_ipapi", name: "ip-api", applies: Kind::Ip, desc: "open in ip-api", url: "https://ip-api.com/#{}", edge: "ip-api" },
    Pivot { id: "pv_ip_whatismyip", name: "WhatIsMyIPAddress", applies: Kind::Ip, desc: "open in WhatIsMyIPAddress", url: "https://whatismyipaddress.com/ip/{}", edge: "wimia" },
    Pivot { id: "pv_ip_maltiverse", name: "Maltiverse IP", applies: Kind::Ip, desc: "open in Maltiverse IP", url: "https://maltiverse.com/ip/{}", edge: "maltiverse" },
    Pivot { id: "pv_email_hibp", name: "Have I Been Pwned", applies: Kind::Email, desc: "open in Have I Been Pwned", url: "https://haveibeenpwned.com/account/{}", edge: "hibp" },
    Pivot { id: "pv_email_hunter", name: "Hunter.io", applies: Kind::Email, desc: "open in Hunter.io", url: "https://hunter.io/email-verifier/{}", edge: "hunter" },
    Pivot { id: "pv_email_emailrep", name: "EmailRep", applies: Kind::Email, desc: "open in EmailRep", url: "https://emailrep.io/{}", edge: "emailrep" },
    Pivot { id: "pv_email_intelx", name: "Intelligence X", applies: Kind::Email, desc: "open in Intelligence X", url: "https://intelx.io/?s={}", edge: "intelx" },
    Pivot { id: "pv_email_dehashed", name: "DeHashed", applies: Kind::Email, desc: "open in DeHashed", url: "https://www.dehashed.com/search?query={}", edge: "dehashed" },
    Pivot { id: "pv_email_epieos", name: "Epieos", applies: Kind::Email, desc: "open in Epieos", url: "https://epieos.com/?q={}", edge: "epieos" },
    Pivot { id: "pv_email_gravatar", name: "Gravatar", applies: Kind::Email, desc: "open in Gravatar", url: "https://en.gravatar.com/{}", edge: "gravatar" },
    Pivot { id: "pv_email_breachdirectory", name: "BreachDirectory", applies: Kind::Email, desc: "open in BreachDirectory", url: "https://breachdirectory.org/?email={}", edge: "breachdirectory" },
    Pivot { id: "pv_email_leakcheck", name: "LeakCheck", applies: Kind::Email, desc: "open in LeakCheck", url: "https://leakcheck.io/?query={}", edge: "leakcheck" },
    Pivot { id: "pv_email_psbdmp", name: "Pastebin dumps", applies: Kind::Email, desc: "open in Pastebin dumps", url: "https://psbdmp.ws/api/search/{}", edge: "psbdmp" },
    Pivot { id: "pv_email_skymem", name: "Skymem", applies: Kind::Email, desc: "open in Skymem", url: "https://www.skymem.info/srch?q={}", edge: "skymem" },
    Pivot { id: "pv_email_snusbase", name: "Snusbase", applies: Kind::Email, desc: "open in Snusbase", url: "https://snusbase.com/search/{}", edge: "snusbase" },
    Pivot { id: "pv_email_google", name: "Google email", applies: Kind::Email, desc: "open in Google email", url: "https://www.google.com/search?q=%22{}%22", edge: "google" },
    Pivot { id: "pv_email_thatsthem", name: "ThatsThem email", applies: Kind::Email, desc: "open in ThatsThem email", url: "https://thatsthem.com/email/{}", edge: "thatsthem" },
    Pivot { id: "pv_email_verifalia", name: "Verifalia", applies: Kind::Email, desc: "open in Verifalia", url: "https://verifalia.com/validate-email?emailAddress={}", edge: "verifalia" },
    Pivot { id: "pv_email_emailhippo", name: "Email Hippo", applies: Kind::Email, desc: "open in Email Hippo", url: "https://tools.emailhippo.com/?email={}", edge: "emailhippo" },
    Pivot { id: "pv_email_spycloud", name: "SpyCloud check", applies: Kind::Email, desc: "open in SpyCloud check", url: "https://spycloud.com/check-your-exposure/?email={}", edge: "spycloud" },
    Pivot { id: "pv_email_ghunt", name: "GHunt (Google)", applies: Kind::Email, desc: "open in GHunt (Google)", url: "https://www.google.com/search?q={}+site%3Aplus.google.com", edge: "ghunt" },
    Pivot { id: "pv_user_github", name: "GitHub", applies: Kind::Username, desc: "open in GitHub", url: "https://github.com/{}", edge: "github" },
    Pivot { id: "pv_user_gitlab", name: "GitLab", applies: Kind::Username, desc: "open in GitLab", url: "https://gitlab.com/{}", edge: "gitlab" },
    Pivot { id: "pv_user_twitter", name: "X / Twitter", applies: Kind::Username, desc: "open in X / Twitter", url: "https://x.com/{}", edge: "x" },
    Pivot { id: "pv_user_instagram", name: "Instagram", applies: Kind::Username, desc: "open in Instagram", url: "https://instagram.com/{}", edge: "instagram" },
    Pivot { id: "pv_user_reddit", name: "Reddit", applies: Kind::Username, desc: "open in Reddit", url: "https://reddit.com/user/{}", edge: "reddit" },
    Pivot { id: "pv_user_telegram", name: "Telegram", applies: Kind::Username, desc: "open in Telegram", url: "https://t.me/{}", edge: "telegram" },
    Pivot { id: "pv_user_tiktok", name: "TikTok", applies: Kind::Username, desc: "open in TikTok", url: "https://www.tiktok.com/@{}", edge: "tiktok" },
    Pivot { id: "pv_user_youtube", name: "YouTube", applies: Kind::Username, desc: "open in YouTube", url: "https://www.youtube.com/@{}", edge: "youtube" },
    Pivot { id: "pv_user_twitch", name: "Twitch", applies: Kind::Username, desc: "open in Twitch", url: "https://www.twitch.tv/{}", edge: "twitch" },
    Pivot { id: "pv_user_steam", name: "Steam", applies: Kind::Username, desc: "open in Steam", url: "https://steamcommunity.com/id/{}", edge: "steam" },
    Pivot { id: "pv_user_keybase", name: "Keybase", applies: Kind::Username, desc: "open in Keybase", url: "https://keybase.io/{}", edge: "keybase" },
    Pivot { id: "pv_user_medium", name: "Medium", applies: Kind::Username, desc: "open in Medium", url: "https://medium.com/@{}", edge: "medium" },
    Pivot { id: "pv_user_pinterest", name: "Pinterest", applies: Kind::Username, desc: "open in Pinterest", url: "https://www.pinterest.com/{}", edge: "pinterest" },
    Pivot { id: "pv_user_facebook", name: "Facebook", applies: Kind::Username, desc: "open in Facebook", url: "https://www.facebook.com/{}", edge: "facebook" },
    Pivot { id: "pv_user_vk", name: "VK", applies: Kind::Username, desc: "open in VK", url: "https://vk.com/{}", edge: "vk" },
    Pivot { id: "pv_user_soundcloud", name: "SoundCloud", applies: Kind::Username, desc: "open in SoundCloud", url: "https://soundcloud.com/{}", edge: "soundcloud" },
    Pivot { id: "pv_user_spotify", name: "Spotify", applies: Kind::Username, desc: "open in Spotify", url: "https://open.spotify.com/user/{}", edge: "spotify" },
    Pivot { id: "pv_user_flickr", name: "Flickr", applies: Kind::Username, desc: "open in Flickr", url: "https://www.flickr.com/people/{}", edge: "flickr" },
    Pivot { id: "pv_user_vimeo", name: "Vimeo", applies: Kind::Username, desc: "open in Vimeo", url: "https://vimeo.com/{}", edge: "vimeo" },
    Pivot { id: "pv_user_patreon", name: "Patreon", applies: Kind::Username, desc: "open in Patreon", url: "https://www.patreon.com/{}", edge: "patreon" },
    Pivot { id: "pv_user_hackernews", name: "Hacker News", applies: Kind::Username, desc: "open in Hacker News", url: "https://news.ycombinator.com/user?id={}", edge: "hn" },
    Pivot { id: "pv_user_devto", name: "DEV.to", applies: Kind::Username, desc: "open in DEV.to", url: "https://dev.to/{}", edge: "dev.to" },
    Pivot { id: "pv_user_replit", name: "Replit", applies: Kind::Username, desc: "open in Replit", url: "https://replit.com/@{}", edge: "replit" },
    Pivot { id: "pv_user_npm", name: "npm", applies: Kind::Username, desc: "open in npm", url: "https://www.npmjs.com/~{}", edge: "npm" },
    Pivot { id: "pv_user_pypi", name: "PyPI", applies: Kind::Username, desc: "open in PyPI", url: "https://pypi.org/user/{}", edge: "pypi" },
    Pivot { id: "pv_user_dockerhub", name: "Docker Hub", applies: Kind::Username, desc: "open in Docker Hub", url: "https://hub.docker.com/u/{}", edge: "dockerhub" },
    Pivot { id: "pv_user_gitee", name: "Gitee", applies: Kind::Username, desc: "open in Gitee", url: "https://gitee.com/{}", edge: "gitee" },
    Pivot { id: "pv_user_bitbucket", name: "Bitbucket", applies: Kind::Username, desc: "open in Bitbucket", url: "https://bitbucket.org/{}", edge: "bitbucket" },
    Pivot { id: "pv_user_codepen", name: "CodePen", applies: Kind::Username, desc: "open in CodePen", url: "https://codepen.io/{}", edge: "codepen" },
    Pivot { id: "pv_user_kaggle", name: "Kaggle", applies: Kind::Username, desc: "open in Kaggle", url: "https://www.kaggle.com/{}", edge: "kaggle" },
    Pivot { id: "pv_user_behance", name: "Behance", applies: Kind::Username, desc: "open in Behance", url: "https://www.behance.net/{}", edge: "behance" },
    Pivot { id: "pv_user_dribbble", name: "Dribbble", applies: Kind::Username, desc: "open in Dribbble", url: "https://dribbble.com/{}", edge: "dribbble" },
    Pivot { id: "pv_user_whatsmyname", name: "WhatsMyName", applies: Kind::Username, desc: "open in WhatsMyName", url: "https://whatsmyname.app/?q={}", edge: "whatsmyname" },
    Pivot { id: "pv_user_namechk", name: "Namechk", applies: Kind::Username, desc: "open in Namechk", url: "https://namechk.com/{}", edge: "namechk" },
    Pivot { id: "pv_user_sherlock", name: "Sherlock (search)", applies: Kind::Username, desc: "open in Sherlock (search)", url: "https://www.google.com/search?q=%22{}%22+profile", edge: "sherlock" },
    Pivot { id: "pv_phone_truecaller", name: "Truecaller", applies: Kind::Phone, desc: "open in Truecaller", url: "https://www.truecaller.com/search/global/{}", edge: "truecaller" },
    Pivot { id: "pv_phone_syncme", name: "Sync.me", applies: Kind::Phone, desc: "open in Sync.me", url: "https://sync.me/search/?number={}", edge: "sync.me" },
    Pivot { id: "pv_phone_numlookup", name: "NumLookup", applies: Kind::Phone, desc: "open in NumLookup", url: "https://www.numlookup.com/results?phone={}", edge: "numlookup" },
    Pivot { id: "pv_phone_whitepages", name: "Whitepages", applies: Kind::Phone, desc: "open in Whitepages", url: "https://www.whitepages.com/phone/{}", edge: "whitepages" },
    Pivot { id: "pv_phone_spydialer", name: "SpyDialer", applies: Kind::Phone, desc: "open in SpyDialer", url: "https://www.spydialer.com/default.aspx?p={}", edge: "spydialer" },
    Pivot { id: "pv_phone_phonevalidator", name: "PhoneValidator", applies: Kind::Phone, desc: "open in PhoneValidator", url: "https://www.phonevalidator.com/results.aspx?number={}", edge: "phonevalidator" },
    Pivot { id: "pv_phone_tellows", name: "tellows", applies: Kind::Phone, desc: "open in tellows", url: "https://www.tellows.com/num/{}", edge: "tellows" },
    Pivot { id: "pv_phone_whocalledme", name: "Who-Called", applies: Kind::Phone, desc: "open in Who-Called", url: "https://who-called.co.uk/Number/{}", edge: "who-called" },
    Pivot { id: "pv_phone_nuwber", name: "Nuwber", applies: Kind::Phone, desc: "open in Nuwber", url: "https://nuwber.com/search?phone={}", edge: "nuwber" },
    Pivot { id: "pv_phone_google", name: "Google phone", applies: Kind::Phone, desc: "open in Google phone", url: "https://www.google.com/search?q=%22{}%22", edge: "google" },
    Pivot { id: "pv_phone_freecarrier", name: "Free Carrier Lookup", applies: Kind::Phone, desc: "open in Free Carrier Lookup", url: "https://www.google.com/search?q=carrier+lookup+{}", edge: "freecarrierlookup" },
    Pivot { id: "pv_phone_numverify", name: "NumVerify", applies: Kind::Phone, desc: "open in NumVerify", url: "https://www.google.com/search?q=numverify+{}", edge: "numverify" },
    Pivot { id: "pv_person_google", name: "Google", applies: Kind::Person, desc: "open in Google", url: "https://www.google.com/search?q=%22{}%22", edge: "google" },
    Pivot { id: "pv_person_bing", name: "Bing", applies: Kind::Person, desc: "open in Bing", url: "https://www.bing.com/search?q=%22{}%22", edge: "bing" },
    Pivot { id: "pv_person_duckduckgo", name: "DuckDuckGo", applies: Kind::Person, desc: "open in DuckDuckGo", url: "https://duckduckgo.com/?q=%22{}%22", edge: "ddg" },
    Pivot { id: "pv_person_linkedin", name: "LinkedIn", applies: Kind::Person, desc: "open in LinkedIn", url: "https://www.linkedin.com/search/results/people/?keywords={}", edge: "linkedin" },
    Pivot { id: "pv_person_pipl", name: "Pipl", applies: Kind::Person, desc: "open in Pipl", url: "https://pipl.com/search/?q={}", edge: "pipl" },
    Pivot { id: "pv_person_thatsthem", name: "ThatsThem", applies: Kind::Person, desc: "open in ThatsThem", url: "https://thatsthem.com/name/{}", edge: "thatsthem" },
    Pivot { id: "pv_person_spokeo", name: "Spokeo", applies: Kind::Person, desc: "open in Spokeo", url: "https://www.spokeo.com/{}", edge: "spokeo" },
    Pivot { id: "pv_person_beenverified", name: "BeenVerified", applies: Kind::Person, desc: "open in BeenVerified", url: "https://www.beenverified.com/people/{}", edge: "beenverified" },
    Pivot { id: "pv_person_fastpeople", name: "FastPeopleSearch", applies: Kind::Person, desc: "open in FastPeopleSearch", url: "https://www.fastpeoplesearch.com/name/{}", edge: "fastpeoplesearch" },
    Pivot { id: "pv_person_truepeople", name: "TruePeopleSearch", applies: Kind::Person, desc: "open in TruePeopleSearch", url: "https://www.truepeoplesearch.com/results?name={}", edge: "truepeoplesearch" },
    Pivot { id: "pv_person_radaris", name: "Radaris", applies: Kind::Person, desc: "open in Radaris", url: "https://radaris.com/p/{}", edge: "radaris" },
    Pivot { id: "pv_person_peekyou", name: "PeekYou", applies: Kind::Person, desc: "open in PeekYou", url: "https://www.peekyou.com/{}", edge: "peekyou" },
    Pivot { id: "pv_person_zabasearch", name: "ZabaSearch", applies: Kind::Person, desc: "open in ZabaSearch", url: "https://www.zabasearch.com/people/{}", edge: "zabasearch" },
    Pivot { id: "pv_person_twitter", name: "X search", applies: Kind::Person, desc: "open in X search", url: "https://x.com/search?q={}", edge: "x" },
    Pivot { id: "pv_person_facebook", name: "Facebook search", applies: Kind::Person, desc: "open in Facebook search", url: "https://www.facebook.com/search/people/?q={}", edge: "facebook" },
    Pivot { id: "pv_person_github", name: "GitHub search", applies: Kind::Person, desc: "open in GitHub search", url: "https://github.com/search?q={}&type=users", edge: "github" },
    Pivot { id: "pv_person_wikipedia", name: "Wikipedia", applies: Kind::Person, desc: "open in Wikipedia", url: "https://en.wikipedia.org/w/index.php?search={}", edge: "wikipedia" },
    Pivot { id: "pv_person_yandex", name: "Yandex", applies: Kind::Person, desc: "open in Yandex", url: "https://yandex.com/search/?text=%22{}%22", edge: "yandex" },
    Pivot { id: "pv_org_opencorporates", name: "OpenCorporates", applies: Kind::Organization, desc: "open in OpenCorporates", url: "https://opencorporates.com/companies?q={}", edge: "opencorporates" },
    Pivot { id: "pv_org_crunchbase", name: "Crunchbase", applies: Kind::Organization, desc: "open in Crunchbase", url: "https://www.crunchbase.com/textsearch?q={}", edge: "crunchbase" },
    Pivot { id: "pv_org_linkedin", name: "LinkedIn company", applies: Kind::Organization, desc: "open in LinkedIn company", url: "https://www.linkedin.com/search/results/companies/?keywords={}", edge: "linkedin" },
    Pivot { id: "pv_org_secedgar", name: "SEC EDGAR", applies: Kind::Organization, desc: "open in SEC EDGAR", url: "https://www.sec.gov/cgi-bin/browse-edgar?company={}&action=getcompany", edge: "sec" },
    Pivot { id: "pv_org_glassdoor", name: "Glassdoor", applies: Kind::Organization, desc: "open in Glassdoor", url: "https://www.glassdoor.com/Search/results.htm?keyword={}", edge: "glassdoor" },
    Pivot { id: "pv_org_google", name: "Google", applies: Kind::Organization, desc: "open in Google", url: "https://www.google.com/search?q=%22{}%22", edge: "google" },
    Pivot { id: "pv_org_github", name: "GitHub org", applies: Kind::Organization, desc: "open in GitHub org", url: "https://github.com/{}", edge: "github" },
    Pivot { id: "pv_org_bbb", name: "BBB", applies: Kind::Organization, desc: "open in BBB", url: "https://www.bbb.org/search?find_text={}", edge: "bbb" },
    Pivot { id: "pv_org_dnb", name: "Dun & Bradstreet", applies: Kind::Organization, desc: "open in Dun & Bradstreet", url: "https://www.dnb.com/business-directory/company-search.html?term={}", edge: "dnb" },
    Pivot { id: "pv_org_twitter", name: "X", applies: Kind::Organization, desc: "open in X", url: "https://x.com/search?q={}", edge: "x" },
    Pivot { id: "pv_btc_blockchaincom", name: "Blockchain.com", applies: Kind::BtcAddress, desc: "open in Blockchain.com", url: "https://www.blockchain.com/explorer/addresses/btc/{}", edge: "blockchain.com" },
    Pivot { id: "pv_btc_blockchair", name: "Blockchair", applies: Kind::BtcAddress, desc: "open in Blockchair", url: "https://blockchair.com/bitcoin/address/{}", edge: "blockchair" },
    Pivot { id: "pv_btc_oxt", name: "OXT", applies: Kind::BtcAddress, desc: "open in OXT", url: "https://oxt.me/address/{}", edge: "oxt" },
    Pivot { id: "pv_btc_walletexplorer", name: "WalletExplorer", applies: Kind::BtcAddress, desc: "open in WalletExplorer", url: "https://www.walletexplorer.com/address/{}", edge: "walletexplorer" },
    Pivot { id: "pv_btc_btccom", name: "BTC.com", applies: Kind::BtcAddress, desc: "open in BTC.com", url: "https://explorer.btc.com/btc/address/{}", edge: "btc.com" },
    Pivot { id: "pv_btc_blockstream", name: "Blockstream", applies: Kind::BtcAddress, desc: "open in Blockstream", url: "https://blockstream.info/address/{}", edge: "blockstream" },
    Pivot { id: "pv_btc_bitref", name: "BitRef", applies: Kind::BtcAddress, desc: "open in BitRef", url: "https://bitref.com/{}", edge: "bitref" },
    Pivot { id: "pv_btc_mempool", name: "mempool.space", applies: Kind::BtcAddress, desc: "open in mempool.space", url: "https://mempool.space/address/{}", edge: "mempool" },
    Pivot { id: "pv_eth_etherscan", name: "Etherscan", applies: Kind::EthAddress, desc: "open in Etherscan", url: "https://etherscan.io/address/{}", edge: "etherscan" },
    Pivot { id: "pv_eth_ethplorer", name: "Ethplorer", applies: Kind::EthAddress, desc: "open in Ethplorer", url: "https://ethplorer.io/address/{}", edge: "ethplorer" },
    Pivot { id: "pv_eth_blockchair", name: "Blockchair ETH", applies: Kind::EthAddress, desc: "open in Blockchair ETH", url: "https://blockchair.com/ethereum/address/{}", edge: "blockchair" },
    Pivot { id: "pv_eth_oklink", name: "OKLink", applies: Kind::EthAddress, desc: "open in OKLink", url: "https://www.oklink.com/eth/address/{}", edge: "oklink" },
    Pivot { id: "pv_eth_debank", name: "DeBank", applies: Kind::EthAddress, desc: "open in DeBank", url: "https://debank.com/profile/{}", edge: "debank" },
    Pivot { id: "pv_eth_zerion", name: "Zerion", applies: Kind::EthAddress, desc: "open in Zerion", url: "https://app.zerion.io/{}/overview", edge: "zerion" },
    Pivot { id: "pv_eth_etherchain", name: "Etherchain", applies: Kind::EthAddress, desc: "open in Etherchain", url: "https://www.etherchain.org/account/{}", edge: "etherchain" },
    Pivot { id: "pv_tx_blockchair", name: "Blockchair tx", applies: Kind::Transaction, desc: "open in Blockchair tx", url: "https://blockchair.com/search?q={}", edge: "blockchair" },
    Pivot { id: "pv_tx_etherscan", name: "Etherscan tx", applies: Kind::Transaction, desc: "open in Etherscan tx", url: "https://etherscan.io/tx/{}", edge: "etherscan" },
    Pivot { id: "pv_tx_blockstream", name: "Blockstream tx", applies: Kind::Transaction, desc: "open in Blockstream tx", url: "https://blockstream.info/tx/{}", edge: "blockstream" },
    Pivot { id: "pv_tx_mempool", name: "mempool.space tx", applies: Kind::Transaction, desc: "open in mempool.space tx", url: "https://mempool.space/tx/{}", edge: "mempool" },
    Pivot { id: "pv_hash_virustotal", name: "VirusTotal hash", applies: Kind::Hash, desc: "open in VirusTotal hash", url: "https://www.virustotal.com/gui/file/{}", edge: "virustotal" },
    Pivot { id: "pv_hash_hybrid", name: "Hybrid Analysis", applies: Kind::Hash, desc: "open in Hybrid Analysis", url: "https://www.hybrid-analysis.com/search?query={}", edge: "hybrid-analysis" },
    Pivot { id: "pv_hash_malwarebazaar", name: "MalwareBazaar", applies: Kind::Hash, desc: "open in MalwareBazaar", url: "https://bazaar.abuse.ch/browse.php?search={}", edge: "malwarebazaar" },
    Pivot { id: "pv_hash_threatminer", name: "ThreatMiner hash", applies: Kind::Hash, desc: "open in ThreatMiner hash", url: "https://www.threatminer.org/sample.php?q={}", edge: "threatminer" },
    Pivot { id: "pv_hash_otx", name: "OTX hash", applies: Kind::Hash, desc: "open in OTX hash", url: "https://otx.alienvault.com/indicator/file/{}", edge: "otx" },
    Pivot { id: "pv_hash_maltiverse", name: "Maltiverse hash", applies: Kind::Hash, desc: "open in Maltiverse hash", url: "https://maltiverse.com/sample/{}", edge: "maltiverse" },
    Pivot { id: "pv_cve_nvd", name: "NVD", applies: Kind::Cve, desc: "open in NVD", url: "https://nvd.nist.gov/vuln/detail/{}", edge: "nvd" },
    Pivot { id: "pv_cve_mitre", name: "MITRE", applies: Kind::Cve, desc: "open in MITRE", url: "https://cve.mitre.org/cgi-bin/cvename.cgi?name={}", edge: "mitre" },
    Pivot { id: "pv_cve_cvedetails", name: "CVE Details", applies: Kind::Cve, desc: "open in CVE Details", url: "https://www.cvedetails.com/cve/{}/", edge: "cvedetails" },
    Pivot { id: "pv_cve_vulners", name: "Vulners", applies: Kind::Cve, desc: "open in Vulners", url: "https://vulners.com/cve/{}", edge: "vulners" },
    Pivot { id: "pv_cve_exploitdb", name: "Exploit-DB", applies: Kind::Cve, desc: "open in Exploit-DB", url: "https://www.exploit-db.com/search?cve={}", edge: "exploit-db" },
    Pivot { id: "pv_cve_githubadv", name: "GitHub Advisory", applies: Kind::Cve, desc: "open in GitHub Advisory", url: "https://github.com/advisories?query={}", edge: "github" },
    Pivot { id: "pv_asn_bgphe", name: "Hurricane Electric", applies: Kind::Asn, desc: "open in Hurricane Electric", url: "https://bgp.he.net/{}", edge: "he.net" },
    Pivot { id: "pv_asn_bgpview", name: "BGPView", applies: Kind::Asn, desc: "open in BGPView", url: "https://bgpview.io/asn/{}", edge: "bgpview" },
    Pivot { id: "pv_asn_ipinfo", name: "IPinfo ASN", applies: Kind::Asn, desc: "open in IPinfo ASN", url: "https://ipinfo.io/{}", edge: "ipinfo" },
    Pivot { id: "pv_asn_peeringdb", name: "PeeringDB", applies: Kind::Asn, desc: "open in PeeringDB", url: "https://www.peeringdb.com/search?q={}", edge: "peeringdb" },
    Pivot { id: "pv_asn_robtex", name: "Robtex ASN", applies: Kind::Asn, desc: "open in Robtex ASN", url: "https://www.robtex.com/as/{}.html", edge: "robtex" },
    Pivot { id: "pv_asn_radar", name: "Cloudflare Radar ASN", applies: Kind::Asn, desc: "open in Cloudflare Radar ASN", url: "https://radar.cloudflare.com/{}", edge: "cloudflare" },
    Pivot { id: "pv_mac_macvendors", name: "MacVendors", applies: Kind::MacAddress, desc: "open in MacVendors", url: "https://macvendors.com/query/{}", edge: "macvendors" },
    Pivot { id: "pv_mac_maclookup", name: "MAC Lookup", applies: Kind::MacAddress, desc: "open in MAC Lookup", url: "https://maclookup.app/search/result?mac={}", edge: "maclookup" },
    Pivot { id: "pv_mac_wireshark", name: "Wireshark OUI", applies: Kind::MacAddress, desc: "open in Wireshark OUI", url: "https://www.wireshark.org/tools/oui-lookup.html?oui={}", edge: "wireshark" },
    Pivot { id: "pv_coord_gmaps", name: "Google Maps", applies: Kind::Coordinate, desc: "open in Google Maps", url: "https://www.google.com/maps/search/?api=1&query={}", edge: "gmaps" },
    Pivot { id: "pv_coord_osm", name: "OpenStreetMap", applies: Kind::Coordinate, desc: "open in OpenStreetMap", url: "https://www.openstreetmap.org/search?query={}", edge: "osm" },
    Pivot { id: "pv_coord_bingmaps", name: "Bing Maps", applies: Kind::Coordinate, desc: "open in Bing Maps", url: "https://www.bing.com/maps?q={}", edge: "bing" },
    Pivot { id: "pv_loc_gmaps", name: "Google Maps", applies: Kind::Location, desc: "open in Google Maps", url: "https://www.google.com/maps/search/?api=1&query={}", edge: "gmaps" },
    Pivot { id: "pv_loc_osm", name: "OpenStreetMap", applies: Kind::Location, desc: "open in OpenStreetMap", url: "https://www.openstreetmap.org/search?query={}", edge: "osm" },
    Pivot { id: "pv_loc_wikimapia", name: "Wikimapia", applies: Kind::Location, desc: "open in Wikimapia", url: "https://wikimapia.org/#search={}", edge: "wikimapia" },
    Pivot { id: "pv_loc_geonames", name: "GeoNames", applies: Kind::Location, desc: "open in GeoNames", url: "https://www.geonames.org/search.html?q={}", edge: "geonames" },
    Pivot { id: "pv_dom2_threatbook", name: "ThreatBook", applies: Kind::Domain, desc: "open in ThreatBook", url: "https://threatbook.io/domain/{}", edge: "threatbook" },
    Pivot { id: "pv_dom2_urlquery", name: "urlquery", applies: Kind::Domain, desc: "open in urlquery", url: "https://urlquery.net/search?q={}", edge: "urlquery" },
    Pivot { id: "pv_dom2_sucuri", name: "Sucuri SiteCheck", applies: Kind::Domain, desc: "open in Sucuri SiteCheck", url: "https://sitecheck.sucuri.net/results/{}", edge: "sucuri" },
    Pivot { id: "pv_dom2_observatory", name: "Mozilla Observatory", applies: Kind::Domain, desc: "open in Mozilla Observatory", url: "https://observatory.mozilla.org/analyze/{}", edge: "observatory" },
    Pivot { id: "pv_dom2_securityheaders", name: "SecurityHeaders", applies: Kind::Domain, desc: "open in SecurityHeaders", url: "https://securityheaders.com/?q={}&followRedirects=on", edge: "securityheaders" },
    Pivot { id: "pv_dom2_whatsmydns", name: "WhatsMyDNS", applies: Kind::Domain, desc: "open in WhatsMyDNS", url: "https://www.whatsmydns.net/#A/{}", edge: "whatsmydns" },
    Pivot { id: "pv_dom2_archivetoday", name: "archive.today", applies: Kind::Domain, desc: "open in archive.today", url: "https://archive.ph/https://{}", edge: "archive.today" },
    Pivot { id: "pv_dom2_domainbigdata", name: "DomainBigData", applies: Kind::Domain, desc: "open in DomainBigData", url: "https://domainbigdata.com/{}", edge: "domainbigdata" },
    Pivot { id: "pv_dom2_completedns", name: "CompleteDNS", applies: Kind::Domain, desc: "open in CompleteDNS", url: "https://completedns.com/dns-history/{}", edge: "completedns" },
    Pivot { id: "pv_dom2_silentpush", name: "Silent Push", applies: Kind::Domain, desc: "open in Silent Push", url: "https://explore.silentpush.com/domain/{}", edge: "silentpush" },
    Pivot { id: "pv_dom2_dnsspy", name: "DNS Spy", applies: Kind::Domain, desc: "open in DNS Spy", url: "https://dnsspy.io/scan/{}", edge: "dnsspy" },
    Pivot { id: "pv_dom2_geekflare", name: "Geekflare DNS", applies: Kind::Domain, desc: "open in Geekflare DNS", url: "https://geekflare.com/tools/dns-lookup?domain={}", edge: "geekflare" },
    Pivot { id: "pv_dom2_ptrarchive", name: "PTRArchive", applies: Kind::Domain, desc: "open in PTRArchive", url: "http://ptrarchive.com/tools/search3.htm?label={}", edge: "ptrarchive" },
    Pivot { id: "pv_dom2_threatyeti", name: "ThreatYeti", applies: Kind::Domain, desc: "open in ThreatYeti", url: "https://threatyeti.com/domain/{}", edge: "threatyeti" },
    Pivot { id: "pv_ip2_dbip", name: "DB-IP", applies: Kind::Ip, desc: "open in DB-IP", url: "https://db-ip.com/{}", edge: "db-ip" },
    Pivot { id: "pv_ip2_iknowwhat", name: "IKnowWhatYouDownload", applies: Kind::Ip, desc: "open in IKnowWhatYouDownload", url: "https://iknowwhatyoudownload.com/en/peer/?ip={}", edge: "iknowwhatyoudownload" },
    Pivot { id: "pv_ip2_projecthoneypot", name: "Project Honey Pot", applies: Kind::Ip, desc: "open in Project Honey Pot", url: "https://www.projecthoneypot.org/ip_{}", edge: "projecthoneypot" },
    Pivot { id: "pv_ip2_cleantalk", name: "CleanTalk", applies: Kind::Ip, desc: "open in CleanTalk", url: "https://cleantalk.org/blacklists/{}", edge: "cleantalk" },
    Pivot { id: "pv_ip2_fraudguard", name: "FraudGuard", applies: Kind::Ip, desc: "open in FraudGuard", url: "https://fraudguard.io/?ip={}", edge: "fraudguard" },
    Pivot { id: "pv_ip2_pingeu", name: "Ping.eu", applies: Kind::Ip, desc: "open in Ping.eu", url: "https://ping.eu/ns/{}", edge: "ping.eu" },
    Pivot { id: "pv_ip2_shadowserver", name: "Shadowserver", applies: Kind::Ip, desc: "open in Shadowserver", url: "https://www.shadowserver.org/what-we-do/network-reporting/get-reports/?ip={}", edge: "shadowserver" },
    Pivot { id: "pv_ip2_censysv4", name: "Censys IPv4", applies: Kind::Ip, desc: "open in Censys IPv4", url: "https://search.censys.io/hosts/{}", edge: "censys" },
    Pivot { id: "pv_ip2_iplocation", name: "IPLocation", applies: Kind::Ip, desc: "open in IPLocation", url: "https://www.iplocation.net/ip-lookup?query={}", edge: "iplocation" },
    Pivot { id: "pv_ip2_viewdns_portscan", name: "ViewDNS port scan", applies: Kind::Ip, desc: "open in ViewDNS port scan", url: "https://viewdns.info/portscan/?host={}", edge: "viewdns" },
    Pivot { id: "pv_ip2_criminalip2", name: "Criminal IP banner", applies: Kind::Ip, desc: "open in Criminal IP banner", url: "https://www.criminalip.io/en/asset/report/{}", edge: "criminalip" },
    Pivot { id: "pv_ip2_mxtoolbox_bl", name: "MXToolbox blacklist", applies: Kind::Ip, desc: "open in MXToolbox blacklist", url: "https://mxtoolbox.com/SuperTool.aspx?action=blacklist%3a{}", edge: "mxtoolbox" },
    Pivot { id: "pv_email2_hibp_paste", name: "HIBP pastes", applies: Kind::Email, desc: "open in HIBP pastes", url: "https://haveibeenpwned.com/PasteSearch/{}", edge: "hibp" },
    Pivot { id: "pv_email2_leaklookup", name: "Leak-Lookup", applies: Kind::Email, desc: "open in Leak-Lookup", url: "https://leak-lookup.com/search?query={}", edge: "leak-lookup" },
    Pivot { id: "pv_email2_mailtester", name: "Mailtester", applies: Kind::Email, desc: "open in Mailtester", url: "https://www.mail-tester.com/{}", edge: "mailtester" },
    Pivot { id: "pv_email2_reoon", name: "Reoon verifier", applies: Kind::Email, desc: "open in Reoon verifier", url: "https://emailverifier.reoon.com/?email={}", edge: "reoon" },
    Pivot { id: "pv_email2_clearbit", name: "Clearbit", applies: Kind::Email, desc: "open in Clearbit", url: "https://person.clearbit.com/v2/people/find?email={}", edge: "clearbit" },
    Pivot { id: "pv_email2_fullcontact", name: "FullContact", applies: Kind::Email, desc: "open in FullContact", url: "https://www.fullcontact.com/?email={}", edge: "fullcontact" },
    Pivot { id: "pv_email2_ghostproject", name: "GhostProject", applies: Kind::Email, desc: "open in GhostProject", url: "https://ghostproject.fr/?q={}", edge: "ghostproject" },
    Pivot { id: "pv_email2_scylla", name: "Scylla", applies: Kind::Email, desc: "open in Scylla", url: "https://scylla.sh/search?q=email:{}", edge: "scylla" },
    Pivot { id: "pv_user2_aboutme", name: "About.me", applies: Kind::Username, desc: "open in About.me", url: "https://about.me/{}", edge: "about.me" },
    Pivot { id: "pv_user2_lastfm", name: "Last.fm", applies: Kind::Username, desc: "open in Last.fm", url: "https://www.last.fm/user/{}", edge: "last.fm" },
    Pivot { id: "pv_user2_tryhackme", name: "TryHackMe", applies: Kind::Username, desc: "open in TryHackMe", url: "https://tryhackme.com/p/{}", edge: "tryhackme" },
    Pivot { id: "pv_user2_hackerone", name: "HackerOne", applies: Kind::Username, desc: "open in HackerOne", url: "https://hackerone.com/{}", edge: "hackerone" },
    Pivot { id: "pv_user2_bugcrowd", name: "Bugcrowd", applies: Kind::Username, desc: "open in Bugcrowd", url: "https://bugcrowd.com/{}", edge: "bugcrowd" },
    Pivot { id: "pv_user2_producthunt", name: "Product Hunt", applies: Kind::Username, desc: "open in Product Hunt", url: "https://www.producthunt.com/@{}", edge: "producthunt" },
    Pivot { id: "pv_user2_goodreads", name: "Goodreads", applies: Kind::Username, desc: "open in Goodreads", url: "https://www.goodreads.com/{}", edge: "goodreads" },
    Pivot { id: "pv_user2_letterboxd", name: "Letterboxd", applies: Kind::Username, desc: "open in Letterboxd", url: "https://letterboxd.com/{}", edge: "letterboxd" },
    Pivot { id: "pv_user2_chesscom", name: "Chess.com", applies: Kind::Username, desc: "open in Chess.com", url: "https://www.chess.com/member/{}", edge: "chess.com" },
    Pivot { id: "pv_user2_lichess", name: "Lichess", applies: Kind::Username, desc: "open in Lichess", url: "https://lichess.org/@/{}", edge: "lichess" },
    Pivot { id: "pv_user2_roblox", name: "Roblox", applies: Kind::Username, desc: "open in Roblox", url: "https://www.roblox.com/users/profile?username={}", edge: "roblox" },
    Pivot { id: "pv_user2_fiverr", name: "Fiverr", applies: Kind::Username, desc: "open in Fiverr", url: "https://www.fiverr.com/{}", edge: "fiverr" },
    Pivot { id: "pv_user2_wattpad", name: "Wattpad", applies: Kind::Username, desc: "open in Wattpad", url: "https://www.wattpad.com/user/{}", edge: "wattpad" },
    Pivot { id: "pv_user2_ao3", name: "Archive of Our Own", applies: Kind::Username, desc: "open in Archive of Our Own", url: "https://archiveofourown.org/users/{}", edge: "ao3" },
    Pivot { id: "pv_user2_okru", name: "OK.ru", applies: Kind::Username, desc: "open in OK.ru", url: "https://ok.ru/{}", edge: "ok.ru" },
    Pivot { id: "pv_user2_periscope", name: "Periscope", applies: Kind::Username, desc: "open in Periscope", url: "https://www.pscp.tv/{}", edge: "periscope" },
    Pivot { id: "pv_user2_mastodon_social", name: "Mastodon (.social)", applies: Kind::Username, desc: "open in Mastodon (.social)", url: "https://mastodon.social/@{}", edge: "mastodon" },
    Pivot { id: "pv_user2_xbox", name: "Xbox Gamertag", applies: Kind::Username, desc: "open in Xbox Gamertag", url: "https://xboxgamertag.com/search/{}", edge: "xbox" },
    Pivot { id: "pv_user2_gravatar_user2", name: "Gravatar profile", applies: Kind::Username, desc: "open in Gravatar profile", url: "https://gravatar.com/{}", edge: "gravatar" },
    Pivot { id: "pv_user2_itch", name: "itch.io", applies: Kind::Username, desc: "open in itch.io", url: "https://{}.itch.io/", edge: "itch.io" },
    Pivot { id: "pv_phone2_eyecon", name: "Eyecon", applies: Kind::Phone, desc: "open in Eyecon", url: "https://www.google.com/search?q=eyecon+{}", edge: "eyecon" },
    Pivot { id: "pv_phone2_calleridtest", name: "CallerID Test", applies: Kind::Phone, desc: "open in CallerID Test", url: "https://calleridtest.com/?number={}", edge: "calleridtest" },
    Pivot { id: "pv_phone2_nuwber2", name: "Nuwber phone", applies: Kind::Phone, desc: "open in Nuwber phone", url: "https://nuwber.com/search?phone={}", edge: "nuwber" },
    Pivot { id: "pv_phone2_usphonebook", name: "US Phonebook", applies: Kind::Phone, desc: "open in US Phonebook", url: "https://www.usphonebook.com/{}", edge: "usphonebook" },
    Pivot { id: "pv_person2_webmii", name: "WebMii", applies: Kind::Person, desc: "open in WebMii", url: "https://webmii.com/people?n={}", edge: "webmii" },
    Pivot { id: "pv_person2_socialsearcher", name: "Social Searcher", applies: Kind::Person, desc: "open in Social Searcher", url: "https://www.social-searcher.com/search-users/?q5={}", edge: "social-searcher" },
    Pivot { id: "pv_person2_usersearch", name: "UserSearch", applies: Kind::Person, desc: "open in UserSearch", url: "https://usersearch.org/results_normal.php?URL_username={}", edge: "usersearch" },
    Pivot { id: "pv_person2_infotracer", name: "Infotracer", applies: Kind::Person, desc: "open in Infotracer", url: "https://www.infotracer.com/name/{}", edge: "infotracer" },
    Pivot { id: "pv_person2_yandex", name: "Yandex", applies: Kind::Person, desc: "open in Yandex", url: "https://yandex.com/search/?text=%22{}%22", edge: "yandex" },
    Pivot { id: "pv_org2_zoominfo", name: "ZoomInfo", applies: Kind::Organization, desc: "open in ZoomInfo", url: "https://www.zoominfo.com/s/#!search/company/{}", edge: "zoominfo" },
    Pivot { id: "pv_org2_northdata", name: "North Data", applies: Kind::Organization, desc: "open in North Data", url: "https://www.northdata.com/_search?query={}", edge: "northdata" },
    Pivot { id: "pv_org2_aihit", name: "aiHit", applies: Kind::Organization, desc: "open in aiHit", url: "https://www.aihitdata.com/companies?q={}", edge: "aihit" },
    Pivot { id: "pv_org2_kompass", name: "Kompass", applies: Kind::Organization, desc: "open in Kompass", url: "https://www.kompass.com/searchCompanies?text={}", edge: "kompass" },
    Pivot { id: "pv_btc2_blockcypher", name: "BlockCypher", applies: Kind::BtcAddress, desc: "open in BlockCypher", url: "https://live.blockcypher.com/btc/address/{}/", edge: "blockcypher" },
    Pivot { id: "pv_btc2_btcscan", name: "BTCScan", applies: Kind::BtcAddress, desc: "open in BTCScan", url: "https://btcscan.org/address/{}", edge: "btcscan" },
    Pivot { id: "pv_btc2_bitinfocharts", name: "BitInfoCharts", applies: Kind::BtcAddress, desc: "open in BitInfoCharts", url: "https://bitinfocharts.com/bitcoin/address/{}", edge: "bitinfocharts" },
    Pivot { id: "pv_btc2_breadcrumbs", name: "Breadcrumbs", applies: Kind::BtcAddress, desc: "open in Breadcrumbs", url: "https://www.breadcrumbs.app/reports/{}", edge: "breadcrumbs" },
    Pivot { id: "pv_btc2_tokenview", name: "TokenView", applies: Kind::BtcAddress, desc: "open in TokenView", url: "https://btc.tokenview.io/en/address/{}", edge: "tokenview" },
    Pivot { id: "pv_eth2_ethplorer2", name: "Ethplorer top", applies: Kind::EthAddress, desc: "open in Ethplorer top", url: "https://ethplorer.io/address/{}#chart=candlestick", edge: "ethplorer" },
    Pivot { id: "pv_eth2_breadcrumbs_eth", name: "Breadcrumbs ETH", applies: Kind::EthAddress, desc: "open in Breadcrumbs ETH", url: "https://www.breadcrumbs.app/reports/{}", edge: "breadcrumbs" },
    Pivot { id: "pv_eth2_arkham", name: "Arkham", applies: Kind::EthAddress, desc: "open in Arkham", url: "https://platform.arkhamintelligence.com/explorer/address/{}", edge: "arkham" },
    Pivot { id: "pv_eth2_bloxy", name: "Bloxy", applies: Kind::EthAddress, desc: "open in Bloxy", url: "https://bloxy.info/address/{}", edge: "bloxy" },
    Pivot { id: "pv_hash2_filescan", name: "FileScan.io", applies: Kind::Hash, desc: "open in FileScan.io", url: "https://www.filescan.io/search-result?query={}", edge: "filescan" },
    Pivot { id: "pv_hash2_intezer", name: "Intezer", applies: Kind::Hash, desc: "open in Intezer", url: "https://analyze.intezer.com/files/{}", edge: "intezer" },
    Pivot { id: "pv_hash2_polyswarm", name: "PolySwarm", applies: Kind::Hash, desc: "open in PolySwarm", url: "https://polyswarm.network/scan/results/file/{}", edge: "polyswarm" },
    Pivot { id: "pv_hash2_valhalla", name: "Valhalla", applies: Kind::Hash, desc: "open in Valhalla", url: "https://valhalla.nextron-systems.com/info/hash/{}", edge: "valhalla" },
    Pivot { id: "pv_hash2_filescanio", name: "MalShare search", applies: Kind::Hash, desc: "open in MalShare search", url: "https://malshare.com/search.php?query={}", edge: "malshare" },
    Pivot { id: "pv_cve2_snyk", name: "Snyk", applies: Kind::Cve, desc: "open in Snyk", url: "https://security.snyk.io/vuln?search={}", edge: "snyk" },
    Pivot { id: "pv_cve2_attackerkb", name: "AttackerKB", applies: Kind::Cve, desc: "open in AttackerKB", url: "https://attackerkb.com/search?q={}", edge: "attackerkb" },
    Pivot { id: "pv_cve2_packetstorm", name: "Packet Storm", applies: Kind::Cve, desc: "open in Packet Storm", url: "https://packetstormsecurity.com/search/?q={}", edge: "packetstorm" },
    Pivot { id: "pv_cve2_opencve", name: "OpenCVE", applies: Kind::Cve, desc: "open in OpenCVE", url: "https://www.opencve.io/cve/{}", edge: "opencve" },
    Pivot { id: "pv_asn2_asrank", name: "CAIDA AS Rank", applies: Kind::Asn, desc: "open in CAIDA AS Rank", url: "https://asrank.caida.org/asns/{}", edge: "asrank" },
    Pivot { id: "pv_asn2_ipinfo_asn2", name: "IPinfo ASN", applies: Kind::Asn, desc: "open in IPinfo ASN", url: "https://ipinfo.io/{}", edge: "ipinfo" },
    Pivot { id: "pv_asn2_hurricane2", name: "Hurricane peers", applies: Kind::Asn, desc: "open in Hurricane peers", url: "https://bgp.he.net/{}#_peers", edge: "he.net" },
    Pivot { id: "pv_mac2_dnschecker_mac", name: "DNSChecker MAC", applies: Kind::MacAddress, desc: "open in DNSChecker MAC", url: "https://dnschecker.org/mac-lookup.php?query={}", edge: "dnschecker" },
    Pivot { id: "pv_mac2_aruljohn", name: "ArulJohn MAC", applies: Kind::MacAddress, desc: "open in ArulJohn MAC", url: "https://aruljohn.com/mac/{}", edge: "aruljohn" },

];

/// Pivot definitions exposed as TransformDefs (built once, leaked as 'static).
pub fn defs() -> &'static [TransformDef] {
    static D: OnceLock<Vec<TransformDef>> = OnceLock::new();
    D.get_or_init(|| PIVOTS.iter()
        .map(|p| TransformDef { id: p.id, name: p.name, applies: p.applies, desc: p.desc })
        .collect())
}

/// If `id` is a pivot, build its URL for `value`. Returns (url, edge_label).
pub fn run(id: &str, value: &str) -> Option<(String, &'static str)> {
    let p = PIVOTS.iter().find(|p| p.id == id)?;
    Some((p.url.replace("{}", &enc(value.trim())), p.edge))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn pivots_are_well_formed() {
        let mut ids = HashSet::new();
        for p in PIVOTS {
            assert!(ids.insert(p.id), "duplicate pivot id: {}", p.id);
            assert!(p.url.starts_with("https://") || p.url.starts_with("http://"),
                "{} url must be http(s): {}", p.id, p.url);
            assert!(p.url.contains("{}"), "{} url missing placeholder: {}", p.id, p.url);
            assert!(!p.name.is_empty() && !p.edge.is_empty(), "{} missing name/edge", p.id);
            let built = run(p.id, "example").expect("pivot runs").0;
            assert!(!built.contains("{}"), "{} placeholder left unfilled", p.id);
            assert!(built.contains("example"), "{} did not substitute the value", p.id);
        }
        assert!(PIVOTS.len() >= 200, "expected 200+ pivots, got {}", PIVOTS.len());
    }
}

/// True if `id` is a pivot applicable to `kind`.
pub fn applies(id: &str, kind: Kind) -> bool {
    PIVOTS.iter().any(|p| p.id == id && p.applies == kind)
}

/// Minimal URL-component percent-encoding.
fn enc(s: &str) -> String {
    let mut o = String::new();
    for b in s.bytes() {
        match b {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => o.push(b as char),
            _ => o.push_str(&format!("%{b:02X}")),
        }
    }
    o
}
